#!/usr/bin/env python3
# ==============================================================================
# 03_vfio_isolation.py
# Purpose: Dynamic GPU Passthrough Isolation. Configures modprobe drop-ins,
#          mkinitcpio, and surgically injects kernel parameters into bootloaders.
# Target: Python 3.14+ 
# ==============================================================================
import os
import sys
import subprocess
import threading
import time
import re
from pathlib import Path

CYAN, GREEN, YELLOW, RED, NC = '\033[1;36m', '\033[1;32m', '\033[1;33m', '\033[1;31m', '\033[0m'

def log_info(msg: str) -> None: print(f"{CYAN}[INFO]{NC} {msg}")
def log_warn(msg: str) -> None: print(f"{YELLOW}[WARN]{NC} {msg}")
def log_success(msg: str) -> None: print(f"{GREEN}[SUCCESS]{NC} {msg}")
def log_error(msg: str) -> None:
    print(f"{RED}[ERROR]{NC} {msg}")
    sys.exit(1)

def sudo_keep_alive() -> None:
    """Daemon thread to refresh sudo credentials invisibly."""
    while True:
        subprocess.run(["sudo", "-n", "true"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
        time.sleep(60)

def validate_environment() -> None:
    if os.geteuid() != 0:
        log_error("Root privileges required. Execute via sudo.")
    threading.Thread(target=sudo_keep_alive, daemon=True).start()

def detect_iommu_type() -> str:
    try:
        cpuinfo = Path('/proc/cpuinfo').read_text().lower()
        if 'intel' in cpuinfo:
            log_info("Detected Intel Architecture.")
            return "intel_iommu=on iommu=pt"
        elif 'amd' in cpuinfo:
            log_info("Detected AMD Architecture.")
            return "amd_iommu=on iommu=pt"
    except FileNotFoundError:
        pass
    
    log_warn("CPU Vendor indeterminate. Falling back to generic IOMMU pass-through.")
    return "iommu=pt"

def configure_modprobe(gpu_id: str, audio_id: str) -> None:
    log_info("Deploying modprobe interception rules...")
    vfio_conf = Path('/etc/modprobe.d/vfio.conf')
    
    content = f"""# Generated by Arch Orchestrator
options vfio-pci ids={gpu_id},{audio_id}
softdep nvidia pre: vfio-pci
softdep nouveau pre: vfio-pci
blacklist nouveau
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
"""
    vfio_conf.write_text(content, encoding='utf-8')
    log_success("Modprobe interception applied.")

def configure_mkinitcpio() -> None:
    log_info("Deploying mkinitcpio early-load drop-in...")
    dropin_dir = Path('/etc/mkinitcpio.conf.d')
    dropin_dir.mkdir(parents=True, exist_ok=True)
    
    dropin_file = dropin_dir / '15-vfio.conf'
    dropin_file.write_text("# Generated by Arch Orchestrator\nMODULES=(vfio_pci vfio vfio_iommu_type1)\n", encoding='utf-8')
    dropin_file.chmod(0o644)
    log_success(f"Drop-in created at {dropin_file}.")

def inject_bootloader_params(vfio_params: str, gpu_id: str) -> None:
    log_info("Analyzing bootloader architecture for kernel parameter injection...")
    
    # 1. Base cmdline / Limine
    cmdline_path = Path("/etc/kernel/cmdline")
    if cmdline_path.exists():
        log_info("Detected generic kernel cmdline architecture.")
        current_cmdline = cmdline_path.read_text(encoding='utf-8').strip()
        if gpu_id not in current_cmdline:
            cmdline_path.with_suffix('.bak').write_text(current_cmdline, encoding='utf-8')
            cmdline_path.write_text(f"{current_cmdline} {vfio_params}\n", encoding='utf-8')
            log_success("Injected into /etc/kernel/cmdline.")
            if subprocess.run(["command", "-v", "limine-update"], capture_output=True, shell=True).returncode == 0:
                subprocess.run(["limine-update"], check=False)
        else:
            log_success("Parameters already exist in cmdline. Skipping injection.")
        return

    # 2. systemd-boot
    systemd_entries_dir = Path("/boot/loader/entries")
    if systemd_entries_dir.is_dir() and any(systemd_entries_dir.iterdir()):
        log_info("Detected systemd-boot architecture.")
        for conf_file in systemd_entries_dir.glob("*.conf"):
            content = conf_file.read_text(encoding='utf-8')
            if re.search(r"^options\s", content, re.MULTILINE):
                if gpu_id not in content:
                    updated_content = re.sub(
                        r"^(options\s+.*)$", 
                        rf"\1 {vfio_params}", 
                        content, 
                        flags=re.MULTILINE
                    )
                    conf_file.write_text(updated_content, encoding='utf-8')
                    log_success(f"Injected into {conf_file.name}.")
                else:
                    log_success(f"Parameters already exist in {conf_file.name}.")
        subprocess.run(["bootctl", "update"], check=False, stderr=subprocess.DEVNULL)
        return

    # 3. GRUB
    grub_path = Path("/etc/default/grub")
    if grub_path.exists():
        log_info("Detected GRUB architecture.")
        content = grub_path.read_text(encoding='utf-8')
        if gpu_id not in content:
            grub_path.with_suffix('.bak').write_text(content, encoding='utf-8')
            updated_content = re.sub(
                r'^(GRUB_CMDLINE_LINUX_DEFAULT=")(.*?)(")$',
                rf'\1\2 {vfio_params}\3',
                content,
                flags=re.MULTILINE
            )
            grub_path.write_text(updated_content, encoding='utf-8')
            subprocess.run(["grub-mkconfig", "-o", "/boot/grub/grub.cfg"], check=True)
            log_success("Injected into GRUB configuration.")
        else:
            log_success("Parameters already exist in GRUB. Skipping injection.")
        return

    log_error("Bootloader indeterminable. Manual parameter injection required.")

def main() -> None:
    print(f"{CYAN}===================================================={NC}")
    print(f"{CYAN}          GPU VFIO Isolation Configuration          {NC}")
    print(f"{CYAN}===================================================={NC}")
    
    choice = input("Configure GPU Passthrough (VFIO Isolation)? [y/N]: ").strip().lower()
    if choice not in ('y', 'yes'):
        log_info("Skipping GPU isolation gracefully.")
        sys.exit(0)

    validate_environment()
    log_warn("MUX Switch laptops MUST have BIOS set to Hybrid/iGPU mode to prevent black screens.")
    
    log_info("Scanning PCIe topology for Display/Audio controllers...")
    subprocess.run("lspci -nn | grep -iE 'vga|3d|display|audio'", shell=True)
    
    print("\n")
    gpu_id = input("Enter Vendor:Product ID of GPU to isolate (e.g., 10de:25a0): ").strip()
    audio_id = input("Enter Vendor:Product ID of Audio Controller (e.g., 10de:2291): ").strip()
    
    if not gpu_id or not audio_id:
        log_error("Hardware IDs cannot be null. Precise IOMMU grouping requires both.")

    iommu_param = detect_iommu_type()
    vfio_params = f"{iommu_param} vfio-pci.ids={gpu_id},{audio_id} modprobe.blacklist=nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm,nouveau"

    configure_modprobe(gpu_id, audio_id)
    configure_mkinitcpio()
    inject_bootloader_params(vfio_params, gpu_id)
    
    log_info("Baking VFIO modules into the unified kernel image / initramfs...")
    subprocess.run(["mkinitcpio", "-P"], check=True)
    
    print(f"\n{GREEN}=== GPU Isolation Complete ==={NC}")
    print(f"{YELLOW}System reboot required for hardware bindings to lock.{NC}")

if __name__ == "__main__":
    main()
