-- =============================================================================
-- USER CONFIGURATION: appearance.lua
-- =============================================================================
-- Add your custom appearance settings here.
-- These will override or add to the defaults found in
-- ~/.config/hypr/source/appearance.lua
-- This file can also be edited with:
--   dusky appearance  (from the Rofi menu or Dusky Control Center)
-- =============================================================================

local home = os.getenv("HOME")

-- THEME SOURCE: Load colors generated by Matugen
dofile(home .. "/.config/matugen/generated/hyprland-colors.lua")

-- -------------------------------------------------------------------------------------------------
-- 1. GENERAL APPEARANCE — override defaults
-- -------------------------------------------------------------------------------------------------
hl.config({
    general = {
        gaps_in          = 6,
        gaps_out         = 12,
        gaps_workspaces  = 0,
        border_size      = 2,

        -- Colors from Matugen (globals set by hyprland-colors.lua above)
        col = {
            active_border   = primary,
            inactive_border = inverse_on_surface,
        },

        resize_on_border = false,
        allow_tearing    = true,
        layout           = "dwindle",

        snap = {
            enabled      = false,
            window_gap   = 10,
            monitor_gap  = 10,
            border_overlap = false,
        },
    },
})

-- -------------------------------------------------------------------------------------------------
-- 2. DECORATION
-- -------------------------------------------------------------------------------------------------
hl.config({
    decoration = {
        rounding       = 6,
        rounding_power = 6.0,

        active_opacity    = 0.8,
        inactive_opacity  = 0.6,
        fullscreen_opacity = 1.0,

        dim_inactive = true,
        dim_strength = 0.2,
        dim_special  = 0.8,

        shadow = {
            enabled      = true,
            range        = 35,
            render_power = 2,
            sharp        = false,
            scale        = 1.0,
            color        = "rgba(1a1a1aee)",
        },

        blur = {
            enabled           = true,
            size              = 4,
            passes            = 2,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = true,

            noise      = 0.0217,
            contrast   = 0.8916,
            brightness = 0.8172,
            vibrancy   = 0.1696,

            popups = false,
        },
    },
})

-- -------------------------------------------------------------------------------------------------
-- 3. ANIMATIONS — load the currently active preset
-- -------------------------------------------------------------------------------------------------
dofile(home .. "/.config/hypr/source/animations/active/active.lua")

-- -------------------------------------------------------------------------------------------------
-- 4. LAYOUTS
-- -------------------------------------------------------------------------------------------------
hl.config({
    dwindle = { preserve_split = true },
    master  = { new_status = "master" },
})

-- -------------------------------------------------------------------------------------------------
-- 5. MISCELLANEOUS & PERFORMANCE
-- -------------------------------------------------------------------------------------------------
hl.config({
    misc = {
        force_default_wallpaper  = 1,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
    },
})

-- -------------------------------------------------------------------------------------------------
-- 6. BINDS (Visual specific)
-- -------------------------------------------------------------------------------------------------
hl.config({
    binds = { allow_pin_fullscreen = true },
})

-- -------------------------------------------------------------------------------------------------
-- 7. SMART GAPS (Single Window Override)
-- Applied automatically when only 1 window is tiled or fullscreened on a workspace.
-- -------------------------------------------------------------------------------------------------
local single_window_gap = 10
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = single_window_gap, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = single_window_gap, gaps_in = 0 })
