-- =============================================================================
-- USER CONFIGURATION: keybinds.lua
-- =============================================================================
-- Add your custom keybinds here.
-- These will override or add to the defaults found in
-- ~/.config/hypr/source/keybinds.lua
-- This file can also be edited with:
--   dusky keybinds manager  (from the Rofi menu or Dusky Control Center)
-- =============================================================================

local mainMod = "SUPER"
local home    = os.getenv("HOME")

-- App variables come from edit_here/source/default_apps.lua (loaded first)

-- Auto-generated by FM Switcher
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("uwsm-app " .. fileManager), { description = "File Manager" })

-- Auto-generated by Browser Switcher
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("uwsm-app -- " .. browser), { description = "Launch Browser" })

-- Auto-generated by Text Editor Switcher
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("uwsm-app " .. textEditor), { description = "Open Text Editor" })

-- Auto-generated by Terminal Switcher
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("uwsm-app -- " .. terminal), { description = "Launch Terminal" })

-- Override the base clipboard bind: terminal-based clipboard manager
-- First remove the base bind (rofi clipboard), then set the terminal one:
hl.unbind(mainMod .. " + V")
hl.bind(mainMod .. " + V",
    hl.dsp.exec_cmd(home .. "/user_scripts/clipboard/close_terminal_clipboard.sh uwsm-app -- kitty --class terminal_clipboard.sh -e " .. home .. "/user_scripts/clipboard/terminal_clipboard.sh"),
    { description = "Clipboard History" })

-- =========================================
-- GAMING MODE (Submap Passthrough)
-- =========================================
-- Press Super + F12 to disable all Hyprland binds.
hl.bind(mainMod .. " + F12", hl.dsp.submap("clean"))

hl.define_submap("clean", function()
    -- The ONLY keybind that works in this state is the one to exit it
    hl.bind(mainMod .. " + F12", hl.dsp.submap("reset"))
end)
