-- =============================================================================
-- USER CONFIGURATION: monitors.lua
-- =============================================================================
-- Generated by Dusky Monitor Wizard on 20260321_114029
-- Configure your monitors here.  Edit with:
--   dusky appearance → Monitor Setup
-- =============================================================================

-- Performance: enable Variable Frame Rate via the debug block
hl.config({ debug = { vfr = true } })

-- Monitor Rules
hl.monitor({ output = "DP-1",      mode = "1920x1080@144.00", position = "0x0", scale = 1 })
hl.monitor({ output = "HEADLESS-2", disabled = true })
