#!/usr/bin/env python3
"""
🦊 Dusky Sites Setup Script (Arch Linux / Python 3.12+)
========================================================
Automated setup script for MatugenFox Native Messaging Host, Native UI,
desktop entry synchronization, and browser profile provisioning.
"""

import sys
import os
import json
import stat
import shutil
import subprocess
from pathlib import Path

# --- Terminal Styling ---
C_CYAN = '\033[0;36m'
C_GREEN = '\033[0;32m'
C_BLUE = '\033[0;34m'
C_YELLOW = '\033[1;33m'
C_RED = '\033[0;31m'
C_RESET = '\033[0m'

def print_step(msg: str): print(f"{C_BLUE}==>{C_RESET} {msg}")
def print_success(msg: str): print(f"{C_GREEN}✓{C_RESET} {msg}")
def print_warn(msg: str): print(f"{C_YELLOW}⚠{C_RESET} {msg}")
def print_error(msg: str): print(f"{C_RED}❌ Error:{C_RESET} {msg}"); sys.exit(1)

def setup_user_chrome(home: Path):
    """Automates Firefox right-click context menu & chrome UI theming using Lightweight Theme architecture"""
    browser_dirs = [
        home / ".mozilla" / "firefox",
        home / ".config" / "mozilla" / "firefox",
        home / ".librewolf",
        home / ".config" / "librewolf",
        home / ".zen",
        home / ".config" / "zen",
        home / ".waterfox",
        home / ".floorp",
        home / ".firedragon",
        home / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
        home / ".var" / "app" / "io.gitlab.librewolf-community" / ".librewolf",
    ]

    pref_line = 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'

    menu_css_content = """/* Auto-generated by MatugenFox — Native Context Menu & Chrome UI */
:root {
    --zen-primary-color: var(--lwt-accent-color) !important;
    --zen-accent-primary: var(--lwt-accent-color) !important;
    --zen-background: var(--lwt-accent-color) !important;
    --zen-text: var(--lwt-text-color) !important;
}

#navigator-toolbox,
#zen-appcontent-wrapper {
    background: var(--lwt-accent-color) !important;
}

menupopup,
panel {
    appearance: none !important;
    -moz-default-appearance: none !important;
    --panel-background-color: var(--lwt-accent-color) !important;
    --panel-background: var(--lwt-accent-color) !important;
    --panel-text-color: var(--lwt-text-color) !important;
    --panel-color: var(--lwt-text-color) !important;
    --panel-border-color: var(--toolbar-field-border, var(--lwt-accent-color)) !important;
    --menu-background-color: var(--lwt-accent-color) !important;
    --menu-color: var(--lwt-text-color) !important;
    --menu-border-color: var(--toolbar-field-border, var(--lwt-accent-color)) !important;
}

menupopup::part(content) {
    background-color: var(--lwt-accent-color) !important;
    color: var(--lwt-text-color) !important;
    border: 1px solid var(--toolbar-field-border, var(--lwt-accent-color)) !important;
}

menu,
menuitem {
    appearance: none !important;
    -moz-default-appearance: none !important;
    border-radius: 6px !important;
    padding: 6px 12px !important;
    background-color: transparent !important;
    color: var(--lwt-text-color) !important;
    transition: background-color 120ms ease, color 120ms ease;
}

menu:is(:hover, [_moz-menuactive="true"]):not([disabled]),
menuitem:is(:hover, [_moz-menuactive="true"]):not([disabled]) {
    background-color: var(--toolbarbutton-hover-background, var(--toolbarbutton-background-color-hover, rgba(255,255,255,0.1))) !important;
    color: var(--toolbarbutton-icon-fill, var(--lwt-text-color)) !important;
}

menubar > menu[open] {
    border-bottom: 2px solid var(--tab-loading-fill, var(--lwt-text-color)) !important;
}

menuseparator::before {
    border-top: 1px solid var(--toolbar-field-border, rgba(255,255,255,0.15)) !important;
}

menuitem[disabled] {
    opacity: 0.4 !important;
}

menuitem[type="checkbox"] > .menu-icon,
menuitem[type="radio"] > .menu-icon {
    appearance: none !important;
    -moz-default-appearance: none !important;
    width: 14px !important;
    height: 14px !important;
    display: inline-block !important;
    box-sizing: border-box !important;
    content: "" !important;
    list-style-image: none !important;
    -moz-context-properties: fill, fill-opacity;
    border: 1px solid transparent !important;
    outline: none !important;
    box-shadow: none !important;
    background-color: var(--toolbar-field-background-color, rgba(255,255,255,0.1)) !important;
    border-radius: 50%;
    transition: all 120ms ease;
}

menuitem[type="checkbox"] > .menu-icon {
    border-radius: 4px;
}

menuitem[type="checkbox"][checked] > .menu-icon,
menuitem[type="radio"][checked] > .menu-icon {
    background-color: var(--toolbarbutton-icon-fill, var(--lwt-text-color)) !important;
}

menuitem:is(:hover, [_moz-menuactive="true"]) > .menu-icon {
    border-color: var(--toolbarbutton-icon-fill, var(--lwt-text-color)) !important;
}

menuitem:is(:hover, [_moz-menuactive="true"])[checked] > .menu-icon {
    filter: brightness(1.1);
}
"""

    installed_profiles = 0
    for base_dir in browser_dirs:
        if not base_dir.is_dir():
            continue
        for profile in base_dir.glob("*"):
            if not profile.is_dir():
                continue
            if not ('.' in profile.name or 'default' in profile.name.lower() or (profile / "prefs.js").is_file()):
                continue

            # 1. Enable toolkit.legacyUserProfileCustomizations.stylesheets
            user_js = profile / "user.js"
            if user_js.is_file():
                content = user_js.read_text(encoding='utf-8')
                if pref_line not in content:
                    user_js.write_text(content + f"\n{pref_line}\n", encoding='utf-8')
            else:
                user_js.write_text(f"{pref_line}\n", encoding='utf-8')

            # 2. Chrome directory & menu styling
            chrome_dir = profile / "chrome"
            chrome_dir.mkdir(parents=True, exist_ok=True)

            menu_css = chrome_dir / "dusky_menu.css"
            menu_css.write_text(menu_css_content, encoding='utf-8')

            user_chrome = chrome_dir / "userChrome.css"
            import_line = '@import url("dusky_menu.css");'

            if user_chrome.is_file():
                existing = user_chrome.read_text(encoding='utf-8')
                if import_line not in existing:
                    user_chrome.write_text(f"{import_line}\n\n" + existing, encoding='utf-8')
            else:
                user_chrome.write_text(f"{import_line}\n", encoding='utf-8')

            installed_profiles += 1

    if installed_profiles > 0:
        print_success(f"Context menu styling injected into {installed_profiles} profile(s).")
    else:
        print_warn("No profile directories found for context menu styling.")

def main():
    print(f"\n{C_CYAN}🦊 Dusky Sites Setup Script (Arch Linux / Python 3.12+){C_RESET}\n")

    home = Path.home()
    script_dir = home / ".config" / "firefox_extentions" / "matugenfox"
    if not script_dir.is_dir():
        script_dir = Path(__file__).parent.resolve()

    host_path = script_dir / "matugenfox_host.py"
    manifest_name = "matugenfox.json"

    print_step("Performing pre-flight checks...")
    if not host_path.is_file():
        print_error(f"Host script not found at {host_path}")
    print_success("Pre-flight checks passed.")

    # 1. Host Execution Permissions
    print_step("Securing host script permissions...")
    try:
        st = host_path.stat()
        host_path.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print_success("Host script is now executable.")
    except Exception as e:
        print_error(f"Failed to set executable permissions: {e}")

    # 2. Intelligent Directory Provisioning (XDG Standard)
    print_step("Provisioning configuration directories...")
    
    config_dir = home / ".config" / "dusky" / "settings" / "matugenfox"
    config_dir.mkdir(parents=True, exist_ok=True)
    
    config_file = config_dir / "config.json"
    if not config_file.is_file():
        config_data = {
            "colorsPath": "~/.config/matugen/generated/firefox_websites.css",
            "websitesDir": "~/.config/dusky_sites",
            "webThemeEnabled": False,
            "ecoMode": True,
            "browserThemeEnabled": True,
            "userChromeEnabled": True,
            "userContentEnabled": True,
            "disabledSites": []
        }
        config_file.write_text(json.dumps(config_data, indent=2), encoding='utf-8')
        print_success(f"Created primary config file at {config_file}")
    else:
        print_success(f"Config file exists at {config_file}")

    dusky_sites_dir = home / ".config" / "dusky_sites"
    dusky_sites_dir.mkdir(parents=True, exist_ok=True)
    print_success(f"Ensured templates directory exists at {dusky_sites_dir}")

    matugen_gen_dir = home / ".config" / "matugen" / "generated"
    matugen_gen_dir.mkdir(parents=True, exist_ok=True)
    print_success(f"Ensured Matugen output directory exists at {matugen_gen_dir}")

    # 3. Multi-Browser Detection (Arch Linux focus)
    print_step("Detecting supported Firefox-based browsers...")
    targets = []

    candidates = [
        ("Firefox", home / ".mozilla"),
        ("Firefox (XDG)", home / ".config" / "mozilla"),
        ("LibreWolf", home / ".librewolf"),
        ("LibreWolf (XDG)", home / ".config" / "librewolf"),
        ("Zen", home / ".zen"),
        ("Zen (XDG)", home / ".config" / "zen"),
        ("Waterfox", home / ".waterfox"),
        ("Floorp", home / ".floorp"),
        ("FireDragon", home / ".firedragon"),
        ("Firefox (Flatpak)", home / ".var" / "app" / "org.mozilla.firefox" / ".mozilla"),
        ("LibreWolf (Flatpak)", home / ".var" / "app" / "io.gitlab.librewolf-community" / ".librewolf"),
    ]
    
    for name, path in candidates:
        nmh_dir = path / "native-messaging-hosts"
        if path.is_dir() or nmh_dir.is_dir():
            targets.append((name, nmh_dir))

    if not targets:
        default_nmh = home / ".mozilla" / "native-messaging-hosts"
        targets.append(("Firefox (Default)", default_nmh))

    # 4. Install Manifests
    print_step("Installing native messaging manifests...")
    manifest_payload = {
        "name": "matugenfox",
        "description": "MatugenFox Native Messaging Host",
        "path": str(host_path),
        "type": "stdio",
        "allowed_extensions": [
            "matugenfox@ubaid.com"
        ]
    }

    installed_count = 0
    for name, target_dir in targets:
        try:
            target_dir.mkdir(parents=True, exist_ok=True)
            manifest_file = target_dir / manifest_name
            manifest_file.write_text(json.dumps(manifest_payload, indent=2), encoding='utf-8')
            print_success(f"Manifest installed for {name} → {target_dir}")
            installed_count += 1
        except Exception as e:
            print_warn(f"Failed to install manifest in {target_dir}: {e}")

    # 5. Context Menu & Native Chrome UI Theming
    print_step("Provisioning native context menu & userChrome styling...")
    setup_user_chrome(home)

    # 6. Synchronize Desktop Launcher
    print_step("Synchronizing Dusky Sites desktop entry...")
    desktop_sync_script = home / "user_scripts" / "arch_setup_scripts" / "scripts" / "020_desktop_entries.py"
    if desktop_sync_script.is_file():
        try:
            subprocess.run([sys.executable, str(desktop_sync_script)], check=True)
            print_success("Desktop entries synchronized successfully.")
        except Exception as e:
            print_warn(f"Could not synchronize desktop entry automatically: {e}")

    # 7. Flatpak Sandbox Overrides (if applicable)
    if shutil.which("flatpak"):
        print_step("Checking for Flatpak browser sandboxes...")
        flatpak_apps = ["org.mozilla.firefox", "io.gitlab.librewolf-community", "io.github.zen_browser.zen", "one.ablaze.floorp"]
        for app in flatpak_apps:
            res = subprocess.run(["flatpak", "info", app], capture_output=True)
            if res.returncode == 0:
                subprocess.run([
                    "flatpak", "override", "--user",
                    f"--filesystem={script_dir}:ro",
                    f"--filesystem={config_dir}:rw",
                    f"--filesystem={matugen_gen_dir}:ro",
                    f"--filesystem={dusky_sites_dir}:ro",
                    app
                ], capture_output=True)
                print_success(f"Applied Flatpak filesystem permissions for {app}")

    # 8. Completion Report
    print(f"\n{C_GREEN}✅ Setup Complete! Dusky Sites was installed into {installed_count} browser target(s).{C_RESET}")
    print("------------------------------------------------------------------")
    print(f"{C_CYAN}1. Load Extension:{C_RESET}   Open about:addons -> Install Add-on From File (.zip / .xpi)")
    print(f"{C_CYAN}2. Open TUI:{C_RESET}          Run ~/user_scripts/firefox/theme_matugen/tui_dusky_sites.py")
    print("------------------------------------------------------------------\n")

if __name__ == "__main__":
    main()
