#!/usr/bin/env bash
# Autonomous Pacman Mirror Orchestrator
# Resolves mirror selection, waits for active pacman locks with a 60s timeout,
# removes stale locks via /proc inspection, runs mirror benchmarking with
# asynchronous visual feedback, and configures systemd timers.
#
# CachyOS Franken-Arch notes (see: https://wiki.cachyos.org/features/optimized_repos/):
#   - cachyos-v3-mirrorlist entries use the literal path segment "x86_64_v3" in URLs.
#     Standard Arch pacman expands $arch as "x86_64", so the mirrorlist shipped by the
#     cachyos-v3-mirrorlist package uses $arch_v3 (a CachyOS pacman extension) OR
#     already contains hardcoded x86_64_v3 paths in newer package versions.
#   - This script patches any remaining $arch/$arch_v3 variables to their literal
#     values as a belt-and-braces safety measure, preventing 404s on standard Arch.
#   - Architecture = auto in pacman.conf is correct — do NOT use "x86_64_v3 x86_64".
#     The mirrorlist files handle arch routing; pacman.conf Architecture only affects
#     which packages pacman considers installable (auto = uname -m = x86_64, which is
#     correct — the v3 repos present packages as x86_64 architecture to pacman).

set -euo pipefail

# --- STRICT ABORT TRAP ---
CURRENT_BG_PID=''
CURRENT_BG_LOG=''

abort_script() {
    printf '\n\033[?25h\033[31m!! User aborted script execution.\033[0m\n' >&2

    if [[ -n ${CURRENT_BG_PID:-} ]] && kill -0 "$CURRENT_BG_PID" 2>/dev/null; then
        kill -TERM -- "-$CURRENT_BG_PID" 2>/dev/null || true

        for _ in {1..20}; do
            kill -0 "$CURRENT_BG_PID" 2>/dev/null || break
            sleep 0.1
        done

        if kill -0 "$CURRENT_BG_PID" 2>/dev/null; then
            kill -KILL -- "-$CURRENT_BG_PID" 2>/dev/null || true
        fi

        wait "$CURRENT_BG_PID" 2>/dev/null || true
    fi

    if [[ -n ${CURRENT_BG_LOG:-} ]]; then
        rm -f -- "$CURRENT_BG_LOG"
    fi

    CURRENT_BG_PID=''
    CURRENT_BG_LOG=''

    exit 1
}

trap abort_script SIGINT SIGTERM

# --- CONFIGURATION ---
readonly PACMAN_LOCK="/var/lib/pacman/db.lck"
readonly TARGET_FILE="/etc/pacman.d/mirrorlist"
readonly REFLECTOR_CONF="/etc/xdg/reflector/reflector.conf"
TARGET_OS=""

# --- GLOBAL FALLBACK STORE ---
# Hardcoded to x86_64 to prevent standard pacman from requesting x86_64_v3
read -r -d '' FALLBACK_MIRRORS << 'EOF' || true
## Global CDN Fallback (Auto-generated by orchestrator)
Server = https://geo.mirror.pkgbuild.com/$repo/os/x86_64
Server = https://fastly.mirror.pkgbuild.com/$repo/os/x86_64
Server = https://mirror.rackspace.com/archlinux/$repo/os/x86_64
EOF

# --- COLORS (TTY Conditional) ---
if [[ -t 1 ]]; then
    readonly G=$'\e[32m' R=$'\e[31m' Y=$'\e[33m' B=$'\e[34m' NC=$'\e[0m'
else
    readonly G="" R="" Y="" B="" NC=""
fi

log_info() { printf '%s:: %s%s\n' "$B" "$1" "$NC"; }
log_ok()   { printf '%s:: %s%s\n' "$G" "$1" "$NC"; }
log_warn() { printf '%s:: %s%s\n' "$Y" "$1" "$NC"; }
log_err()  { printf '%s!! %s%s\n' "$R" "$1" "$NC" >&2; }

# --- ARGUMENT PARSING ---
parse_args() {
    for arg in "$@"; do
        case "$arg" in
            --cachyos|--cachy) TARGET_OS="cachyos" ;;
            --arch)            TARGET_OS="arch" ;;
            --auto|-a)         ;; # Accepted but doesn't change core logic here
            *)                 ;; # Safely ignore unknown flags
        esac
    done
}

# --- ATOMIC FILE WRITER ---
write_text_file_atomic() {
    local target="$1"
    local mode="$2"
    local content="$3"
    local tmp rc

    tmp="$(mktemp "${target}.tmp.XXXXXX")"

    if {
        printf '%s\n' "$content" > "$tmp"
        chmod "$mode" "$tmp"
        mv -f -- "$tmp" "$target"
    }; then
        return 0
    fi

    rc=$?
    rm -f -- "$tmp"
    return "$rc"
}

apply_arch_fallback_mirrorlist() {
    write_text_file_atomic "$TARGET_FILE" 0644 "$FALLBACK_MIRRORS"
}

# --- ASYNCHRONOUS UI WRAPPER ---
run_with_spinner() {
    local msg="$1"
    shift

    local tmp_log pid rc
    tmp_log="$(mktemp)"
    CURRENT_BG_LOG=$tmp_log

    setsid -w -- "$@" </dev/null > "$tmp_log" 2>&1 &
    pid=$!
    CURRENT_BG_PID=$pid

    local delay=0.1
    local frames=( '⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏' )

    if [[ -t 1 ]]; then
        printf '\033[?25l'

        while kill -0 "$pid" 2>/dev/null; do
            for frame in "${frames[@]}"; do
                kill -0 "$pid" 2>/dev/null || break
                printf '\r%s::%s %s %s' "$B" "$NC" "$frame" "$msg"
                sleep "$delay"
            done
        done

        printf '\033[?25h\r\033[K'
    fi

    wait "$pid"
    rc=$?

    if (( rc == 0 )); then
        CURRENT_BG_PID=''
        CURRENT_BG_LOG=''
        rm -f -- "$tmp_log"
        return 0
    fi

    CURRENT_BG_PID=''
    CURRENT_BG_LOG=''

    log_warn "Process encountered issues. Reviewing trace:"
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -n "$line" ]] && log_warn "  -> $line"
    done < "$tmp_log"

    rm -f -- "$tmp_log"
    return "$rc"
}

# --- PRE-FLIGHT ---
if (( EUID != 0 )); then
    if ! command -v sudo &>/dev/null; then
        log_err "This script must be run as root, or sudo must be installed and available."
        exit 1
    fi

    log_info "Elevated privileges required. Prompting for sudo password..."
    exec sudo -- "$0" "$@"
fi

# --- LOCK MANAGEMENT ---
manage_pacman_lock() {
    local -a active_pids=()
    local last_report=''
    local current_report=''
    local elapsed_time=0
    local timeout=60

    while [[ -f "$PACMAN_LOCK" ]]; do
        mapfile -t active_pids < <(
            find /proc/[0-9]*/fd -xtype f -lname "$PACMAN_LOCK" -printf '%h\n' 2>/dev/null |
            awk -F/ '{print $3}' |
            sort -u
        )

        if ((${#active_pids[@]})); then
            current_report="${active_pids[*]}"

            if [[ "$current_report" != "$last_report" ]]; then
                log_warn "Lock file detected at ${PACMAN_LOCK}. Active holder PID(s): ${current_report}. Waiting..."
                last_report="$current_report"
            fi

            if (( elapsed_time >= timeout )); then
                log_warn "Timeout of ${timeout}s reached. Forcibly overriding deadlocked pacman instance..."
                rm -f -- "$PACMAN_LOCK"
                log_ok "Active lock forcibly removed."
                break
            fi

            sleep 2
            (( elapsed_time += 2 ))
            continue
        fi

        log_info "Kernel inspection confirms lock is orphaned (stale). Purging..."
        rm -f -- "$PACMAN_LOCK"
        log_ok "Stale lock safely removed."
        break
    done
}

# --- PACMAN WRAPPER ---
run_pacman() {
    local rc tmp_err

    while :; do
        manage_pacman_lock
        tmp_err="$(mktemp)"

        if LC_ALL=C pacman "$@" 2> "$tmp_err"; then
            rm -f -- "$tmp_err"
            return 0
        fi

        rc=$?

        if [[ -s "$tmp_err" ]]; then
            cat -- "$tmp_err" >&2
        fi

        if grep -Fq 'unable to lock database' "$tmp_err" || \
           grep -Fq 'could not lock database' "$tmp_err"; then
            rm -f -- "$tmp_err"
            log_warn "Pacman reported database lock contention. Waiting for the active transaction to finish..."
            continue
        fi

        rm -f -- "$tmp_err"
        return "$rc"
    done
}

# --- OS DETECTION ---
determine_os_state() {
    if [[ -z "${TARGET_OS}" ]]; then
        log_info "Analyzing system state for mirror routing..."

        if grep -qi "ID=cachyos" /etc/os-release 2>/dev/null; then
            log_warn "Pure CachyOS detected."
            TARGET_OS="cachyos"
        elif pacman -Qq cachyos-mirrorlist &>/dev/null; then
            log_ok "Franken-Arch detected (CachyOS packages found on Standard Arch)."
            TARGET_OS="cachyos"
        else
            log_info "Standard Arch Linux detected."
            TARGET_OS="arch"
        fi
    fi
}

# --- CACHYOS KEYRING BOOTSTRAP ---
# Ensures the CachyOS keyring is initialised before any mirror operations.
# This is critical on fresh installs — without it, pacman-key won't trust
# CachyOS-signed packages and all sync operations will fail with signature errors.
ensure_cachyos_keyring() {
    if pacman -Qq cachyos-keyring &>/dev/null; then
        log_info "CachyOS keyring already present, skipping bootstrap."
        return 0
    fi

    log_info "CachyOS keyring not found. Bootstrapping..."

    # Import the CachyOS signing key (fingerprint: F3B607488DB35A47)
    # Source: https://github.com/CachyOS/cachyos-repo-add-script/blob/develop/cachyos-repo.sh
    if ! pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com; then
        log_warn "Failed to receive CachyOS key from keyserver.ubuntu.com. Trying hkps://keys.openpgp.org..."
        pacman-key --recv-keys F3B607488DB35A47 --keyserver hkps://keys.openpgp.org || {
            log_err "Could not import CachyOS signing key. Mirror sync may fail."
            return 1
        }
    fi

    pacman-key --lsign-key F3B607488DB35A47

    # Install keyring and mirrorlist packages directly from the CachyOS CDN.
    # These URLs are the canonical bootstrap path documented by CachyOS:
    # https://wiki.cachyos.org/features/optimized_repos/
    # https://github.com/CachyOS/linux-cachyos (README)
    #
    # Package versions listed here (keyring-20240331-1, mirrorlist-27-1) are the
    # current stable versions as of the script's last audit. They will be superseded
    # by the repository's own updates once the keyring is bootstrapped.
    local mirror_base="https://mirror.cachyos.org/repo/x86_64/cachyos"
    manage_pacman_lock

    if run_pacman -U --needed --noconfirm \
        "${mirror_base}/cachyos-keyring-20240331-1-any.pkg.tar.zst" \
        "${mirror_base}/cachyos-mirrorlist-27-1-any.pkg.tar.zst" \
        "${mirror_base}/cachyos-v3-mirrorlist-27-1-any.pkg.tar.zst"; then
        log_ok "CachyOS keyring and mirrorlist packages bootstrapped."
    else
        log_warn "Keyring bootstrap failed. Will attempt to continue — cachyos-rate-mirrors may still work."
    fi
}

# --- SYSTEMD TIMER CONFIGURATION ---
configure_arch_timer() {
    log_info "Configuring native systemd timer for automated weekly mirror updates..."

    mkdir -p -- "$(dirname -- "$REFLECTOR_CONF")"

    local reflector_config
    read -r -d '' reflector_config <<EOF || true
--save $TARGET_FILE
--protocol https
--latest 50
--fastest 10
--sort rate
--threads 10
--connection-timeout 2
--download-timeout 2
EOF

    if ! write_text_file_atomic "$REFLECTOR_CONF" 0644 "$reflector_config"; then
        log_warn "Failed to write reflector configuration. Skipping reflector.timer management."
        return 0
    fi

    # Disable reflector.timer — the persistent path unit (mirrorlist-arch-patch.path)
    # handles re-patching on any mirrorlist change. Running reflector.timer on top of
    # that would overwrite the patched file and reintroduce $arch variables.
    if systemctl stop --now reflector.timer &>/dev/null; then
        log_warn "Disabled reflector.timer — the persistent path monitor handles repatching."
    else
        log_info "reflector.timer not active, skipping."
    fi
}

# --- MIRRORLIST ARCHITECTURE PATCHER ---
# Root cause of 404 errors on Franken-Arch:
#   Standard Arch pacman expands $arch as "x86_64". The CachyOS v3 mirrorlist
#   packages (cachyos-v3-mirrorlist) ship entries using either $arch_v3 (a
#   CachyOS pacman fork extension) or already-expanded "x86_64_v3". On standard
#   Arch pacman, $arch_v3 is NOT substituted — it's treated as a literal string,
#   so the URL becomes .../os/$arch_v3/... → 404.
#
#   Additionally, if $arch is present in any v3 mirrorlist, it resolves to
#   "x86_64" not "x86_64_v3", fetching packages from the wrong repo tier.
#
#   This patcher hard-codes all variables to their correct literal values,
#   making the mirrorlist work correctly with standard Arch pacman.
patch_mirrorlist_architectures() {
    log_info "Hardcoding architectures to prevent pacman variable evaluation bugs..."

    # 1. Standard Arch mirrors: $arch → x86_64 (this should already be correct,
    #    but belt-and-braces in case reflector or a future update re-introduces it)
    if [[ -f "$TARGET_FILE" ]]; then
        sed -i 's/\$arch/x86_64/g' "$TARGET_FILE"
    fi

    # 2. CachyOS base mirrorlist: $arch → x86_64
    #    The base [cachyos] repo is at repo/x86_64/cachyos — standard arch.
    if [[ -f "/etc/pacman.d/cachyos-mirrorlist" ]]; then
        sed -i 's/\$arch/x86_64/g' "/etc/pacman.d/cachyos-mirrorlist"
    fi

    # 3. CachyOS v3 mirrorlist: two-pass substitution.
    #    Pass 1: $arch_v3 → x86_64_v3  (CachyOS pacman fork variable)
    #    Pass 2: $arch    → x86_64_v3  (standard $arch remaining after pass 1,
    #                                    or entries that only used $arch)
    #    ORDER MATTERS: always replace $arch_v3 before $arch, otherwise pass 2
    #    would corrupt already-correct x86_64_v3 strings.
    if [[ -f "/etc/pacman.d/cachyos-v3-mirrorlist" ]]; then
        sed -i 's/\$arch_v3/x86_64_v3/g' "/etc/pacman.d/cachyos-v3-mirrorlist"
        sed -i 's/\$arch/x86_64_v3/g'    "/etc/pacman.d/cachyos-v3-mirrorlist"
    fi

    log_ok "Architectures successfully patched."

    # 4. Persist the fix via a systemd path unit that re-applies on any change.
    #    This is necessary because cachyos-rate-mirrors and package updates will
    #    overwrite the mirrorlist files, reintroducing the variable strings.
    install_persistent_arch_patch
}

install_persistent_arch_patch() {
    local helper="/usr/local/bin/fix-mirrorlist-arch"

    cat > "$helper" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
# Mirror patch_mirrorlist_architectures logic exactly.
# Pass 1 before pass 2 is mandatory — see comment in patch_mirrorlist_architectures().
sed -i 's/\$arch_v3/x86_64_v3/g' /etc/pacman.d/cachyos-v3-mirrorlist 2>/dev/null || true
sed -i 's/\$arch/x86_64_v3/g'    /etc/pacman.d/cachyos-v3-mirrorlist 2>/dev/null || true
sed -i 's/\$arch/x86_64/g'       /etc/pacman.d/mirrorlist             2>/dev/null || true
sed -i 's/\$arch/x86_64/g'       /etc/pacman.d/cachyos-mirrorlist     2>/dev/null || true
SCRIPT
    chmod +x "$helper"

    cat > /etc/systemd/system/mirrorlist-arch-patch.service << 'SERVICE'
[Unit]
Description=Fix architecture variables in mirrorlists
Documentation=https://wiki.archlinux.org/title/Pacman

[Service]
Type=oneshot
ExecStart=/usr/local/bin/fix-mirrorlist-arch
SERVICE

    cat > /etc/systemd/system/mirrorlist-arch-patch.path << 'PATH_UNIT'
[Unit]
Description=Monitor mirrorlists and reapply architecture variable fixes
Documentation=https://wiki.archlinux.org/title/Pacman

[Path]
PathChanged=/etc/pacman.d/mirrorlist
PathChanged=/etc/pacman.d/cachyos-mirrorlist
PathChanged=/etc/pacman.d/cachyos-v3-mirrorlist

[Install]
WantedBy=multi-user.target
PATH_UNIT

    systemctl daemon-reload
    systemctl enable --now mirrorlist-arch-patch.path &>/dev/null || true
    log_ok "Persistent arch patch monitor (mirrorlist-arch-patch.path) active."
}

# --- CACHYOS SYNC ---
sync_cachyos() {
    log_info "Initializing CachyOS Mirror Sync..."

    # Ensure keyring is present before any pacman operations on CachyOS repos
    ensure_cachyos_keyring

    local attempt
    local max_attempts=3
    local success=0

    if ! command -v cachyos-rate-mirrors &>/dev/null; then
        log_warn "cachyos-rate-mirrors binary missing. Skipping CachyOS mirror ranking and keeping the current mirror configuration."
    else
        for (( attempt = 1; attempt <= max_attempts; attempt++ )); do
            manage_pacman_lock

            if run_with_spinner "Benchmarking CachyOS mirrors..." cachyos-rate-mirrors; then
                success=1
                break
            fi

            if (( attempt < max_attempts )); then
                log_warn "Network latency detected. Retrying in 5 seconds (Attempt $(( attempt + 1 ))/${max_attempts})..."
                sleep 5
            fi
        done

        if (( ! success )); then
            log_err "cachyos-rate-mirrors failed after ${max_attempts} attempts. Continuing with the existing mirror configuration."
        else
            log_ok "CachyOS mirrors optimized."
        fi

        # Disable all competing mirror timers — the persistent path unit handles
        # re-patching, and running multiple timers risks overwriting patched files.
        for bad_timer in cachyos-mirrorlist.timer cachyos-rate-mirrors.timer reflector.timer; do
            if systemctl list-unit-files --type=timer --no-legend --plain 2>/dev/null | awk '{print $1}' | grep -Fxq "$bad_timer"; then
                systemctl stop --now "$bad_timer" &>/dev/null || true
                log_warn "Disabled $bad_timer — the persistent path monitor handles repatching."
            fi
        done
    fi

    # Crucial: Apply the patcher to fix variables BEFORE syncing.
    # cachyos-rate-mirrors writes fresh mirrorlist files after it runs,
    # so the patch must come after the mirror tool finishes.
    patch_mirrorlist_architectures

    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ARCH LINUX SYNC ---
sync_arch() {
    log_info "Initializing Native Arch Mirror Sync..."

    manage_pacman_lock

    if ! command -v reflector &>/dev/null; then
        log_info "Reflector missing. Bootstrapping dependency..."
        if ! run_pacman -Syu --needed --noconfirm reflector; then
            log_warn "Reflector bootstrap failed with current mirrors."
            log_info "Applying highly-available Global CDN Fallback to recover bootstrap..."
            manage_pacman_lock
            apply_arch_fallback_mirrorlist
            patch_mirrorlist_architectures

            if ! run_pacman -Syu --needed --noconfirm reflector; then
                log_warn "Reflector bootstrap still failed. Continuing with fallback mirrorlist."
            fi
        fi
    fi

    if command -v reflector &>/dev/null; then
        local reflector_tmp
        reflector_tmp="$(mktemp "${TARGET_FILE}.tmp.XXXXXX")"

        manage_pacman_lock

        if run_with_spinner "Benchmarking 50 global mirrors (10 threads)..." \
            reflector --latest 50 \
                      --protocol https \
                      --threads 10 \
                      --connection-timeout 2 \
                      --download-timeout 2 \
                      --fastest 10 \
                      --sort rate \
                      --save "$reflector_tmp"; then
            if {
                chmod 0644 "$reflector_tmp"
                mv -f -- "$reflector_tmp" "$TARGET_FILE"
            }; then
                log_ok "Arch mirrors topologically optimized in parallel."
                configure_arch_timer
            else
                rm -f -- "$reflector_tmp"
                log_warn "Generated mirrorlist could not be installed."
                log_info "Applying highly-available Global CDN Fallback to guarantee pipeline integrity..."
                manage_pacman_lock
                apply_arch_fallback_mirrorlist
                log_ok "Global CDN fallback applied."
            fi
        else
            rm -f -- "$reflector_tmp"
            log_warn "Reflector routing error. Bypassing..."
            log_info "Applying highly-available Global CDN Fallback to guarantee pipeline integrity..."
            manage_pacman_lock
            apply_arch_fallback_mirrorlist
            log_ok "Global CDN fallback applied."
        fi
    else
        log_warn "Reflector remains unavailable after bootstrap. Using highly-available Global CDN fallback."
        manage_pacman_lock
        apply_arch_fallback_mirrorlist
        log_ok "Global CDN fallback applied."
    fi

    # Crucial: Apply the patcher to fix variables BEFORE final syncing.
    patch_mirrorlist_architectures

    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ENTRY POINT ---
main() {
    parse_args "$@"

    printf '\n%s:: Commencing Zero-Interaction Mirror Orchestration%s\n' "$B" "$NC"

    manage_pacman_lock
    determine_os_state

    if [[ "${TARGET_OS}" == "cachyos" ]]; then
        sync_cachyos
    else
        sync_arch
    fi

    printf '\n%s:: Orchestration Complete. Yielding execution to next script.%s\n\n' "$G" "$NC"
}

main "$@"
