#!/usr/bin/env bash
# Autonomous Pacman Mirror Orchestrator
# Resolves mirror selection, handles stale pacman locks via /proc inspection,
# and blocks downstream execution until synchronization work is complete.

set -euo pipefail

# --- CONFIGURATION ---
readonly PACMAN_LOCK="/var/lib/pacman/db.lck"
readonly TARGET_FILE="/etc/pacman.d/mirrorlist"

# --- GLOBAL FALLBACK STORE ---
read -r -d '' FALLBACK_MIRRORS << 'EOF' || true
## Global CDN Fallback (Auto-generated by orchestrator)
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
EOF

# --- COLORS (TTY Conditional) ---
if [[ -t 1 ]]; then
    readonly G=$'\e[32m' R=$'\e[31m' Y=$'\e[33m' B=$'\e[34m' NC=$'\e[0m'
else
    readonly G="" R="" Y="" B="" NC=""
fi

log_info() { printf '%s:: %s%s\n' "$B" "$1" "$NC"; }
log_ok()   { printf '%s:: %s%s\n' "$G" "$1" "$NC"; }
log_warn() { printf '%s:: %s%s\n' "$Y" "$1" "$NC"; }
log_err()  { printf '%s!! %s%s\n' "$R" "$1" "$NC" >&2; }

# --- PRE-FLIGHT ---
if (( EUID != 0 )); then
    log_info "Elevated privileges required. Prompting for sudo password..."
    exec sudo -- "$0" "$@"
fi

# --- LOCK MANAGEMENT ---
# Uses /proc fd inspection to distinguish active pacman lock holders from stale locks.
# Implements a 60-second circuit breaker to forcefully remove deadlocked instances.
manage_pacman_lock() {
    local -a active_pids=()
    local last_report=''
    local current_report=''
    local elapsed_time=0
    local timeout=60

    while [[ -f "$PACMAN_LOCK" ]]; do
        mapfile -t active_pids < <(
            find /proc/[0-9]*/fd -xtype f -lname "$PACMAN_LOCK" -printf '%h\n' 2>/dev/null |
            awk -F/ '{print $3}' |
            sort -u
        )

        if ((${#active_pids[@]})); then
            current_report="${active_pids[*]}"
            if [[ "$current_report" != "$last_report" ]]; then
                log_warn "Lock file detected at ${PACMAN_LOCK}. Active holder PID(s): ${current_report}. Waiting..."
                last_report="$current_report"
            fi
            
            if (( elapsed_time >= timeout )); then
                log_warn "Timeout of ${timeout}s reached. Forcibly overriding deadlocked pacman instance..."
                rm -f -- "$PACMAN_LOCK"
                log_ok "Active lock forcibly removed."
                break
            fi

            sleep 2
            (( elapsed_time += 2 ))
            continue
        fi

        log_info "Kernel inspection confirms lock is orphaned (stale). Purging..."
        rm -f -- "$PACMAN_LOCK"
        log_ok "Stale lock safely removed."
        break
    done
}

# --- PACMAN WRAPPER ---
# Avoids the race where the lock is acquired after a pre-check but before pacman starts.
run_pacman() {
    local rc

    while :; do
        manage_pacman_lock

        if pacman "$@"; then
            return 0
        else
            rc=$?
        fi

        if [[ -f "$PACMAN_LOCK" ]]; then
            log_warn "Pacman lock was acquired by another process during transaction startup. Retrying..."
            continue
        fi

        return "$rc"
    done
}

# --- OS DETECTION ---
detect_cachyos() {
    [[ -f /etc/os-release ]] && grep -q '^ID=cachyos$' /etc/os-release
}

# --- CACHYOS SYNC ---
sync_cachyos() {
    log_info "Initializing CachyOS Mirror Sync..."

    if ! command -v cachyos-rate-mirrors &>/dev/null; then
        log_err "cachyos-rate-mirrors binary missing. Aborting."
        exit 1
    fi

    # Network jitter mitigation
    export CURL_OPTIONS="-4"
    local attempt
    local max_attempts=3
    local success=0

    for (( attempt = 1; attempt <= max_attempts; attempt++ )); do
        manage_pacman_lock

        if cachyos-rate-mirrors; then
            success=1
            break
        fi

        if (( attempt < max_attempts )); then
            log_warn "Network latency detected. Retrying in 5 seconds (Attempt $(( attempt + 1 ))/${max_attempts})..."
            sleep 5
        fi
    done

    if (( ! success )); then
        log_err "cachyos-rate-mirrors failed after ${max_attempts} attempts. Bypassing to ensure pipeline continuation."
    else
        log_ok "CachyOS mirrors optimized."
    fi

    # Final database sync
    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ARCH LINUX SYNC ---
sync_arch() {
    log_info "Initializing Native Arch Mirror Sync..."

    manage_pacman_lock

    if ! command -v reflector &>/dev/null; then
        log_info "Reflector missing. Bootstrapping dependency..."
        if ! run_pacman -Syu --needed --noconfirm reflector; then
            log_warn "Reflector bootstrap failed with current mirrors."
            log_info "Applying highly-available Global CDN Fallback to recover bootstrap..."
            manage_pacman_lock
            printf '%s\n' "$FALLBACK_MIRRORS" > "$TARGET_FILE"

            if ! run_pacman -Syu --needed --noconfirm reflector; then
                log_warn "Reflector bootstrap still failed. Continuing with fallback mirrorlist."
            fi
        fi
    fi

    if command -v reflector &>/dev/null; then
        log_info "Benchmarking global network topology (this takes ~10 seconds)..."
        manage_pacman_lock

        if reflector --latest 50 \
                     --protocol https \
                     --fastest 10 \
                     --sort rate \
                     --save "$TARGET_FILE"; then
            log_ok "Arch mirrors topologically optimized."
        else
            log_warn "Reflector encountered an API routing error."
            log_info "Applying highly-available Global CDN Fallback to guarantee pipeline integrity..."
            manage_pacman_lock
            printf '%s\n' "$FALLBACK_MIRRORS" > "$TARGET_FILE"
            log_ok "Global CDN fallback applied."
        fi
    else
        log_warn "Reflector remains unavailable after bootstrap. Using highly-available Global CDN fallback."
        manage_pacman_lock
        printf '%s\n' "$FALLBACK_MIRRORS" > "$TARGET_FILE"
        log_ok "Global CDN fallback applied."
    fi

    # Final database sync
    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ENTRY POINT ---
main() {
    local auto_mode=0

    for arg in "$@"; do
        if [[ "$arg" == "--auto" ]]; then
            auto_mode=1
        fi
    done

    if (( auto_mode )); then
        log_info "Autonomous mode (--auto) explicitly requested."
    fi

    printf '\n%s:: Commencing Zero-Interaction Mirror Orchestration%s\n' "$B" "$NC"

    manage_pacman_lock

    if detect_cachyos; then
        sync_cachyos
    else
        sync_arch
    fi

    printf '\n%s:: Orchestration Complete. Yielding execution to next script.%s\n\n' "$G" "$NC"
}

main "$@"
