#!/usr/bin/env bash
# Autonomous Pacman Mirror Orchestrator
# Resolves mirror selection, handles stale pacman locks via /proc inspection,
# limits timeouts, runs in parallel, and provides asynchronous visual feedback.
# Configures systemd timers for weekly background maintenance.

set -euo pipefail

# --- STRICT ABORT TRAP ---
trap 'printf "\n\033[?25h\033[31m!! User aborted script execution.\033[0m\n" >&2; exit 1' SIGINT SIGTERM

# --- CONFIGURATION ---
readonly PACMAN_LOCK="/var/lib/pacman/db.lck"
readonly TARGET_FILE="/etc/pacman.d/mirrorlist"
readonly REFLECTOR_CONF="/etc/xdg/reflector/reflector.conf"

# --- GLOBAL FALLBACK STORE ---
read -r -d '' FALLBACK_MIRRORS << 'EOF' || true
## Global CDN Fallback (Auto-generated by orchestrator)
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
EOF

# --- COLORS (TTY Conditional) ---
if [[ -t 1 ]]; then
    readonly G=$'\e[32m' R=$'\e[31m' Y=$'\e[33m' B=$'\e[34m' NC=$'\e[0m'
else
    readonly G="" R="" Y="" B="" NC=""
fi

log_info() { printf '%s:: %s%s\n' "$B" "$1" "$NC"; }
log_ok()   { printf '%s:: %s%s\n' "$G" "$1" "$NC"; }
log_warn() { printf '%s:: %s%s\n' "$Y" "$1" "$NC"; }
log_err()  { printf '%s!! %s%s\n' "$R" "$1" "$NC" >&2; }

# --- ASYNCHRONOUS UI WRAPPER ---
run_with_spinner() {
    local msg="$1"
    shift
    local tmp_log
    tmp_log="$(mktemp)"

    "$@" > /dev/null 2> "$tmp_log" &
    local pid=$!

    local delay=0.1
    local frames=( '⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏' )
    
    printf "\033[?25l" 
    
    while kill -0 "$pid" 2>/dev/null; do
        for frame in "${frames[@]}"; do
            if ! kill -0 "$pid" 2>/dev/null; then break; fi
            printf "\r%s::%s %s %s" "$B" "$NC" "$frame" "$msg"
            sleep "$delay"
        done
    done
    
    printf "\033[?25h\r\033[K" 

    if wait "$pid"; then
        rm -f "$tmp_log"
        return 0
    else
        local rc=$?
        log_warn "Process encountered issues. Reviewing trace:"
        while IFS= read -r line; do
            [[ -n "$line" ]] && log_warn "  -> $line"
        done < "$tmp_log"
        rm -f "$tmp_log"
        return "$rc"
    fi
}

# --- PRE-FLIGHT ---
if (( EUID != 0 )); then
    log_info "Elevated privileges required. Prompting for sudo password..."
    exec sudo -- "$0" "$@"
fi

# --- LOCK MANAGEMENT ---
manage_pacman_lock() {
    local -a active_pids=()
    local last_report=''
    local current_report=''
    local elapsed_time=0
    local timeout=60

    while [[ -f "$PACMAN_LOCK" ]]; do
        mapfile -t active_pids < <(
            find /proc/[0-9]*/fd -xtype f -lname "$PACMAN_LOCK" -printf '%h\n' 2>/dev/null |
            awk -F/ '{print $3}' |
            sort -u
        )

        if ((${#active_pids[@]})); then
            current_report="${active_pids[*]}"
            if [[ "$current_report" != "$last_report" ]]; then
                log_warn "Lock file detected at ${PACMAN_LOCK}. Active holder PID(s): ${current_report}. Waiting..."
                last_report="$current_report"
            fi
            
            if (( elapsed_time >= timeout )); then
                log_warn "Timeout of ${timeout}s reached. Forcibly overriding deadlocked pacman instance..."
                rm -f -- "$PACMAN_LOCK"
                log_ok "Active lock forcibly removed."
                break
            fi

            sleep 2
            (( elapsed_time += 2 ))
            continue
        fi

        log_info "Kernel inspection confirms lock is orphaned (stale). Purging..."
        rm -f -- "$PACMAN_LOCK"
        log_ok "Stale lock safely removed."
        break
    done
}

# --- PACMAN WRAPPER ---
run_pacman() {
    local rc
    while :; do
        manage_pacman_lock
        
        if pacman "$@"; then
            return 0
        else
            rc=$?
        fi

        if [[ -f "$PACMAN_LOCK" ]]; then
            log_warn "Pacman lock was acquired by another process during transaction startup. Retrying..."
            continue
        fi
        return "$rc"
    done
}

# --- OS DETECTION ---
detect_cachyos() {
    [[ -f /etc/os-release ]] && grep -q '^ID=cachyos$' /etc/os-release
}

# --- SYSTEMD TIMER CONFIGURATION ---
configure_arch_timer() {
    log_info "Configuring native systemd timer for automated weekly mirror updates..."
    
    mkdir -p "$(dirname "$REFLECTOR_CONF")"
    
    cat <<EOF > "$REFLECTOR_CONF"
--save $TARGET_FILE
--protocol https
--latest 50
--fastest 10
--sort rate
--threads 10
--connection-timeout 2
--download-timeout 2
EOF

    if systemctl enable --now reflector.timer &>/dev/null; then
        log_ok "reflector.timer is now active."
    else
        log_warn "Failed to enable reflector.timer. Check systemctl status."
    fi
}

# --- CACHYOS SYNC ---
sync_cachyos() {
    log_info "Initializing CachyOS Mirror Sync..."

    if ! command -v cachyos-rate-mirrors &>/dev/null; then
        log_err "cachyos-rate-mirrors binary missing. Aborting."
        exit 1
    fi

    export CURL_OPTIONS="-4"
    local attempt
    local max_attempts=3
    local success=0

    for (( attempt = 1; attempt <= max_attempts; attempt++ )); do
        manage_pacman_lock

        if run_with_spinner "Benchmarking CachyOS mirrors..." cachyos-rate-mirrors; then
            success=1
            break
        fi

        if (( attempt < max_attempts )); then
            log_warn "Network latency detected. Retrying in 5 seconds (Attempt $(( attempt + 1 ))/${max_attempts})..."
            sleep 5
        fi
    done

    if (( ! success )); then
        log_err "cachyos-rate-mirrors failed after ${max_attempts} attempts. Bypassing to ensure pipeline continuation."
    else
        log_ok "CachyOS mirrors optimized."
    fi
    
    if systemctl list-unit-files | grep -q 'cachyos-mirrorlist.timer'; then
        systemctl enable --now cachyos-mirrorlist.timer &>/dev/null || true
    fi

    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ARCH LINUX SYNC ---
sync_arch() {
    log_info "Initializing Native Arch Mirror Sync..."

    manage_pacman_lock

    if ! command -v reflector &>/dev/null; then
        log_info "Reflector missing. Bootstrapping dependency..."
        if ! run_pacman -Syu --needed --noconfirm reflector; then
            log_warn "Reflector bootstrap failed with current mirrors."
            log_info "Applying highly-available Global CDN Fallback to recover bootstrap..."
            manage_pacman_lock
            printf '%s\n' "$FALLBACK_MIRRORS" > "$TARGET_FILE"

            if ! run_pacman -Syu --needed --noconfirm reflector; then
                log_warn "Reflector bootstrap still failed. Continuing with fallback mirrorlist."
            fi
        fi
    fi

    if command -v reflector &>/dev/null; then
        manage_pacman_lock

        if run_with_spinner "Benchmarking 50 global mirrors (10 threads)..." \
            reflector --latest 50 \
                      --protocol https \
                      --threads 10 \
                      --connection-timeout 2 \
                      --download-timeout 2 \
                      --fastest 10 \
                      --sort rate \
                      --save "$TARGET_FILE"; then
            log_ok "Arch mirrors topologically optimized in parallel."
            configure_arch_timer
        else
            log_warn "Reflector routing error. Bypassing..."
            log_info "Applying highly-available Global CDN Fallback to guarantee pipeline integrity..."
            manage_pacman_lock
            printf '%s\n' "$FALLBACK_MIRRORS" > "$TARGET_FILE"
            log_ok "Global CDN fallback applied."
        fi
    else
        log_warn "Reflector remains unavailable after bootstrap. Using highly-available Global CDN fallback."
        manage_pacman_lock
        printf '%s\n' "$FALLBACK_MIRRORS" > "$TARGET_FILE"
        log_ok "Global CDN fallback applied."
    fi

    log_info "Synchronizing pacman databases..."
    run_pacman -Syy || log_warn "Pacman database sync returned non-zero, but pipeline will continue."
}

# --- ENTRY POINT ---
main() {
    printf '\n%s:: Commencing Zero-Interaction Mirror Orchestration%s\n' "$B" "$NC"

    manage_pacman_lock

    if detect_cachyos; then
        sync_cachyos
    else
        sync_arch
    fi

    printf '\n%s:: Orchestration Complete. Yielding execution to next script.%s\n\n' "$G" "$NC"
}

main "$@"
