local home = os.getenv("HOME")
local hypr = home .. "/.config/hypr"
local src  = hypr .. "/source"

-- =============================================================================
-- HYPRLAND MAIN CONFIGURATION — Lua entry point
-- =============================================================================
-- User: [dusky]
-- System: UWSM Managed
--
-- DO NOT EDIT THIS FILE.  Configure in:  ~/.config/hypr/edit_here/
-- =============================================================================

-- Default apps — sourced first so $terminal / $browser etc. are available
-- to every subsequent file.
dofile(hypr .. "/edit_here/source/default_apps.lua")

-- 1. MONITORS — must be first; everything (workspaces, scaling, bars)
--    depends on the physical layout being established.
dofile(src .. "/monitors.lua")

-- 2. PERMISSIONS / ECOSYSTEM
dofile(src .. "/permissions.lua")

-- 3. PLUGINS (uncomment if you use hyprpm-managed plugins)
-- dofile(src .. "/plugins.lua")

-- 4. INPUT DEVICES — keyboard, mouse, touchpad, gestures
dofile(src .. "/input.lua")

-- 5. APPEARANCE — gaps, borders, decorations, animations, colors
dofile(src .. "/appearance.lua")

-- 6. WINDOW RULES & LAYER RULES
dofile(src .. "/window_rules.lua")

-- 7. KEYBINDINGS — loaded after rules so all dispatchers are available
dofile(src .. "/keybinds.lua")

-- 8. AUTOSTART — uses uwsm-app wrappers; loaded late so monitor/input/rules
--    are already applied when apps launch.
dofile(src .. "/autostart.lua")

-- 9. ENVIRONMENT VARIABLES
dofile(src .. "/environment_variables.lua")

-- 10. WORKSPACE RULES
dofile(src .. "/workspace_rules.lua")

-- =============================================================================
-- USER OVERRIDES — loaded last to take priority over everything above
-- =============================================================================
dofile(hypr .. "/edit_here/hyprland.lua")
