#!/usr/bin/env python3
"""
🦊 Dusky Sites Setup Script (Arch Linux / Python 3.12+ / Firefox 115+)
======================================================================
Provisions XDG configuration directories, installs native messaging host
to ~/.local/share/dusky-sites/dusky_sites_host.py, parses profiles.ini,
registers native messaging host manifests, and configures userChrome CSS.
"""

from __future__ import annotations

import sys
import os
import re
import json
import shutil
import stat
from pathlib import Path

# Terminal Styling
C_CYAN = "\033[0;36m"
C_GREEN = "\033[0;32m"
C_BLUE = "\033[0;34m"
C_YELLOW = "\033[1;33m"
C_RED = "\033[0;31m"
C_RESET = "\033[0m"

PREF_NAME = "toolkit.legacyUserProfileCustomizations.stylesheets"
PREF_RE = re.compile(rf'user_pref\(\s*"{re.escape(PREF_NAME)}"\s*,\s*(true|false)\s*\)\s*;')
PREF_LINE = f'user_pref("{PREF_NAME}", true);'

HOST_INSTALL_NAME = "dusky_sites_host.py"
MANIFEST_NAME = "dusky_sites.json"
EXTENSION_ID = "dusky_sites@dusk.com"

def print_step(msg: str) -> None: print(f"{C_BLUE}==>{C_RESET} {msg}")
def print_success(msg: str) -> None: print(f"{C_GREEN}✓{C_RESET} {msg}")
def print_warn(msg: str) -> None: print(f"{C_YELLOW}⚠{C_RESET} {msg}")
def print_error(msg: str) -> None: print(f"{C_RED}❌ Error:{C_RESET} {msg}"); sys.exit(1)

def atomic_write_text(path: Path, text: str) -> None:
    """Write text via tempfile + replace (same-directory atomic rename)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)

def ensure_userchrome_pref(user_js: Path) -> bool:
    try:
        if user_js.is_file():
            content = user_js.read_text(encoding="utf-8")
            if PREF_RE.search(content):
                content = PREF_RE.sub(PREF_LINE, content)
            else:
                content = content.rstrip() + f"\n{PREF_LINE}\n"
            if not content.endswith("\n"):
                content += "\n"
            atomic_write_text(user_js, content)
        else:
            atomic_write_text(user_js, PREF_LINE + "\n")
        return True
    except OSError as e:
        print_warn(f"Could not write {user_js}: {e}")
        return False

def iter_firefox_profiles(base_dir: Path):
    """Yield profile directories from profiles.ini; fallback to prefs.js heuristic."""
    ini = base_dir / "profiles.ini"
    if ini.is_file():
        current: dict[str, str] = {}
        try:
            text = ini.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""

        profiles: list[Path] = []
        def consider(cur: dict[str, str]) -> None:
            rel = cur.get("path")
            if not rel:
                return
            p = Path(rel)
            is_relative = cur.get("isrelative", "1") != "0"
            if is_relative:
                profile = base_dir / p
            else:
                profile = p if p.is_absolute() else (base_dir / p)
            try:
                if profile.is_dir():
                    profiles.append(profile.resolve())
            except OSError:
                if profile.is_dir():
                    profiles.append(profile)

        for line in text.splitlines():
            line = line.strip()
            if line.startswith("[") and line.endswith("]"):
                consider(current)
                current = {}
            elif "=" in line:
                k, v = line.split("=", 1)
                current[k.strip().lower()] = v.strip()
        consider(current)

        seen: set[Path] = set()
        for prof in profiles:
            if prof not in seen:
                seen.add(prof)
                yield prof
        return

    try:
        for profile in base_dir.iterdir():
            if profile.is_dir() and (profile / "prefs.js").is_file():
                yield profile
    except OSError:
        return

MENU_CSS_CONTENT = """/* Auto-generated by Dusky Sites — Native Context Menu & Chrome UI */
:root {
    --zen-primary-color: var(--lwt-accent-color) !important;
    --zen-accent-primary: var(--lwt-accent-color) !important;
    --zen-background: var(--lwt-accent-color) !important;
    --zen-text: var(--lwt-text-color) !important;

    --arrowpanel-background: var(--lwt-popup-background-color, var(--lwt-accent-color)) !important;
    --arrowpanel-color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    --arrowpanel-border-color: var(--lwt-popup-border-color, var(--toolbar-field-border, transparent)) !important;
    --panel-item-hover-bgcolor: var(--toolbarbutton-hover-background, rgba(255, 255, 255, 0.1)) !important;
    --panel-item-hover-color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    --panel-separator-color: var(--toolbar-field-border, rgba(255, 255, 255, 0.15)) !important;
}

#navigator-toolbox,
#zen-appcontent-wrapper {
    background: var(--lwt-accent-color) !important;
}

#sidebar-box,
#sidebar-header,
sidebarheader {
    background-color: var(--lwt-sidebar-background-color, var(--lwt-accent-color)) !important;
    color: var(--lwt-sidebar-text-color, var(--lwt-text-color)) !important;
}

menupopup,
panel {
    appearance: none !important;
    -moz-default-appearance: none !important;
    --panel-background-color: var(--lwt-popup-background-color, var(--lwt-accent-color)) !important;
    --panel-background: var(--lwt-popup-background-color, var(--lwt-accent-color)) !important;
    --panel-text-color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    --panel-color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    --panel-border-color: var(--lwt-popup-border-color, var(--toolbar-field-border, var(--lwt-accent-color))) !important;
    --menu-background-color: var(--lwt-popup-background-color, var(--lwt-accent-color)) !important;
    --menu-color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    --menu-border-color: var(--lwt-popup-border-color, var(--toolbar-field-border, var(--lwt-accent-color))) !important;
}

menupopup::part(content) {
    background-color: var(--lwt-popup-background-color, var(--lwt-accent-color)) !important;
    color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    border: 1px solid var(--lwt-popup-border-color, var(--toolbar-field-border, var(--lwt-accent-color))) !important;
}

menu,
menuitem {
    appearance: none !important;
    -moz-default-appearance: none !important;
    border-radius: 6px !important;
    padding: 6px 12px !important;
    background-color: transparent !important;
    color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    transition: background-color 120ms ease, color 120ms ease;
}

menu:is(:hover, [_moz-menuactive="true"]):not([disabled]),
menuitem:is(:hover, [_moz-menuactive="true"]):not([disabled]) {
    background-color: var(--toolbarbutton-hover-background, var(--toolbarbutton-background-color-hover, rgba(255,255,255,0.1))) !important;
    color: var(--toolbarbutton-icon-fill, var(--lwt-popup-color, var(--lwt-text-color))) !important;
}

findbar {
    background-color: var(--lwt-accent-color) !important;
    color: var(--lwt-text-color) !important;
    border-top: 1px solid var(--toolbar-field-border, rgba(255,255,255,0.15)) !important;
}

.findbar-textbox {
    background-color: var(--toolbar-field-background-color, rgba(255,255,255,0.1)) !important;
    color: var(--lwt-text-color) !important;
}

tooltip {
    appearance: none !important;
    background-color: var(--lwt-popup-background-color, var(--lwt-accent-color)) !important;
    color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
    border: 1px solid var(--toolbar-field-border, rgba(255,255,255,0.15)) !important;
    border-radius: 6px !important;
}

.urlbarView-row:is([selected], :hover) {
    background-color: var(--toolbarbutton-hover-background, rgba(255, 255, 255, 0.1)) !important;
    color: var(--lwt-popup-color, var(--lwt-text-color)) !important;
}
"""

def setup_user_chrome(home: Path) -> None:
    browser_dirs = [
        home / ".mozilla" / "firefox",
        home / ".config" / "mozilla" / "firefox",
        home / ".librewolf",
        home / ".config" / "librewolf",
        home / ".zen",
        home / ".config" / "zen",
        home / ".waterfox",
        home / ".floorp",
        home / ".firedragon",
        home / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
        home / ".var" / "app" / "io.gitlab.librewolf-community" / ".librewolf",
    ]

    installed_profiles = 0
    failed_prefs = 0

    for base_dir in browser_dirs:
        if not base_dir.is_dir():
            continue
        for profile in iter_firefox_profiles(base_dir):
            if not ensure_userchrome_pref(profile / "user.js"):
                failed_prefs += 1

            chrome_dir = profile / "chrome"
            try:
                chrome_dir.mkdir(parents=True, exist_ok=True)
                menu_css = chrome_dir / "dusky_menu.css"
                atomic_write_text(menu_css, MENU_CSS_CONTENT)

                user_chrome = chrome_dir / "userChrome.css"
                import_line = '@import url("dusky_menu.css");'
                if user_chrome.is_file():
                    existing = user_chrome.read_text(encoding="utf-8")
                    if import_line not in existing:
                        atomic_write_text(user_chrome, f"{import_line}\n\n{existing}")
                else:
                    atomic_write_text(user_chrome, f"{import_line}\n")
                installed_profiles += 1
            except OSError as e:
                print_warn(f"Could not write chrome CSS in {profile}: {e}")

    if installed_profiles > 0:
        print_success(f"Context menu styling injected into {installed_profiles} profile(s).")
    else:
        print_warn("No profile directories found for context menu styling.")
    if failed_prefs:
        print_warn(f"user.js pref write failed for {failed_prefs} profile(s); userChrome may be inert until fixed.")

def resolve_source_host(script_dir: Path) -> Path:
    candidates = [
        script_dir / HOST_INSTALL_NAME,
        script_dir / "dusky_sites_host.py",
        Path.home() / ".config" / "firefox_extentions" / "matugenfox" / "dusky_sites_host.py",
    ]
    for c in candidates:
        if c.is_file():
            return c
    return candidates[0]

def main() -> None:
    print(f"\n{C_CYAN}🦊 Dusky Sites Setup Script (Arch Linux / Python 3.12+){C_RESET}\n")

    script_dir = Path(__file__).parent.resolve()
    source_host = resolve_source_host(script_dir)

    print_step("Performing pre-flight checks...")
    if not source_host.is_file():
        print_error(f"Host script not found. Place {HOST_INSTALL_NAME} next to this setup script.\n  looked for: {source_host}")
    print_success(f"Found host source at {source_host}")

    home = Path.home()
    data_home = Path(os.environ.get("XDG_DATA_HOME", home / ".local" / "share"))
    install_dir = data_home / "dusky-sites"
    install_dir.mkdir(parents=True, exist_ok=True)
    installed_host = install_dir / HOST_INSTALL_NAME

    print_step("Installing host to stable XDG path...")
    try:
        shutil.copy2(source_host, installed_host)
        installed_host.chmod(0o700)
        legacy = install_dir / "dusky_sites_host.py"
        if legacy.is_file() and legacy.resolve() != installed_host.resolve():
            try:
                legacy.unlink()
            except OSError:
                pass
        print_success(f"Host installed at {installed_host}")
    except OSError as e:
        print_error(f"Failed to install host: {e}")

    print_step("Provisioning configuration directories...")
    config_dir = home / ".config" / "dusky" / "settings" / "matugenfox"
    config_dir.mkdir(parents=True, exist_ok=True)

    config_file = config_dir / "config.json"
    if not config_file.is_file():
        config_data = {
            "colorsPath": "~/.config/matugen/generated/dusky_sites.css",
            "websitesDir": "~/.config/dusky_sites",
            "webThemeEnabled": False,
            "disabledSites": [],
        }
        try:
            atomic_write_text(config_file, json.dumps(config_data, indent=2) + "\n")
            print_success(f"Created primary config file at {config_file}")
        except OSError as e:
            print_error(f"Failed to create config: {e}")
    else:
        print_success(f"Config file exists at {config_file}")

    dusky_sites_dir = home / ".config" / "dusky_sites"
    dusky_sites_dir.mkdir(parents=True, exist_ok=True)
    print_success(f"Ensured templates directory exists at {dusky_sites_dir}")

    matugen_gen_dir = home / ".config" / "matugen" / "generated"
    matugen_gen_dir.mkdir(parents=True, exist_ok=True)
    print_success(f"Ensured Matugen output directory exists at {matugen_gen_dir}")

    print_step("Detecting supported Firefox-based browsers...")
    targets: list[tuple[str, Path]] = []
    candidates = [
        ("Firefox", home / ".mozilla"),
        ("Firefox (XDG)", home / ".config" / "mozilla"),
        ("LibreWolf", home / ".librewolf"),
        ("LibreWolf (XDG)", home / ".config" / "librewolf"),
        ("Zen", home / ".zen"),
        ("Zen (XDG)", home / ".config" / "zen"),
        ("Waterfox", home / ".waterfox"),
        ("Floorp", home / ".floorp"),
        ("FireDragon", home / ".firedragon"),
        ("Firefox (Flatpak)", home / ".var" / "app" / "org.mozilla.firefox" / ".mozilla"),
        ("LibreWolf (Flatpak)", home / ".var" / "app" / "io.gitlab.librewolf-community" / ".librewolf"),
    ]

    for name, path in candidates:
        nmh_dir = path / "native-messaging-hosts"
        if path.is_dir() or nmh_dir.is_dir():
            targets.append((name, nmh_dir))

    if not targets:
        targets.append(("Firefox (Default)", home / ".mozilla" / "native-messaging-hosts"))

    print_step("Installing native messaging manifests...")
    manifest_payload = {
        "name": "dusky_sites",
        "description": "Dusky Sites Native Messaging Host",
        "path": str(installed_host),
        "type": "stdio",
        "allowed_extensions": [EXTENSION_ID],
    }
    manifest_text = json.dumps(manifest_payload, indent=2) + "\n"

    installed_count = 0
    for name, target_dir in targets:
        try:
            target_dir.mkdir(parents=True, exist_ok=True)
            for stale in ("matugenfox.json", "dusky_sites.json"):
                old = target_dir / stale
                if stale != MANIFEST_NAME and old.exists():
                    try:
                        old.unlink()
                    except OSError:
                        pass
            manifest_file = target_dir / MANIFEST_NAME
            atomic_write_text(manifest_file, manifest_text)
            print_success(f"Manifest installed for {name} → {manifest_file}")
            installed_count += 1
        except OSError as e:
            print_warn(f"Failed to install manifest in {target_dir}: {e}")

    if installed_count == 0:
        print_warn("No native messaging manifests were installed.")

    print_step("Provisioning native context menu & userChrome styling...")
    setup_user_chrome(home)

    print(f"\n{C_GREEN}✅ Setup Complete! Dusky Sites host installed cleanly.{C_RESET}")
    print("------------------------------------------------------------------")
    print(f"{C_CYAN}Host path:{C_RESET} {installed_host}")
    print(f"{C_CYAN}Manifest name:{C_RESET} {MANIFEST_NAME} (native app name: dusky_sites)")
    print("------------------------------------------------------------------\n")

if __name__ == "__main__":
    main()
