-- Generated by Matugen — do not edit manually.
-- Source image: {{image}}
-- Regenerate by running: theme_ctl refresh

image = "{{image}}"
<* for name, value in colors *>
{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>
