-- =============================================================================
-- APPEARANCE — Base Configuration
-- =============================================================================
-- DO NOT EDIT THIS FILE.
-- Configure appearance in ~/.config/hypr/edit_here/source/appearance.lua
-- which is loaded last and overrides these defaults.
-- =============================================================================

-- -------------------------------------------------------------------------------------------------
-- 1. GENERAL APPEARANCE
-- Control gaps, borders, and layout behavior.
-- See: https://wiki.hypr.land/Configuring/Variables/#general
-- -------------------------------------------------------------------------------------------------
hl.config({
    general = {
        -- Gaps & Borders
        gaps_in          = 6,      -- Gap between windows
        gaps_out         = 12,     -- Gap between windows and monitor edges
        gaps_workspaces  = 0,      -- Gap between workspaces (when sliding)
        border_size      = 2,      -- Size of window borders

        -- Behavior
        -- resize_on_border: allows resizing by dragging on the gap/border area
        resize_on_border = false,

        -- allow_tearing: lower latency in games
        -- NOTE: also set 'windowrule immediate' on the game class
        allow_tearing = true,

        -- Default layout engine
        layout = "dwindle",

        -- Snapping: controls how floating windows snap to each other and edges
        snap = {
            enabled      = false,
            window_gap   = 10,    -- min gap (px) before snapping to another window
            monitor_gap  = 10,    -- min gap (px) before snapping to monitor edge
            border_overlap = false,
        },
    },
})

-- -------------------------------------------------------------------------------------------------
-- 2. DECORATION
-- Shadows, Blur, Opacity, and Rounding.
-- See: https://wiki.hypr.land/Configuring/Variables/#decoration
-- -------------------------------------------------------------------------------------------------
hl.config({
    decoration = {
        -- Rounding
        rounding       = 6,
        rounding_power = 6.0,

        -- Opacity
        active_opacity    = 0.95,
        inactive_opacity  = 0.8,
        fullscreen_opacity = 1.0,

        -- Dimming
        dim_inactive = false,
        dim_strength = 0.2,
        dim_special  = 0.8,   -- stronger dimming for special workspace

        -- Shadows
        shadow = {
            enabled      = true,
            range        = 35,
            render_power = 2,      -- 1-4; higher = faster falloff (sharper)
            sharp        = false,
            scale        = 1.0,
            color        = "rgba(1a1a1aee)",
        },

        -- Blur
        blur = {
            enabled           = true,
            size              = 4,     -- radius
            passes            = 2,     -- quality (2 = good perf/looks balance)
            new_optimizations = true,
            ignore_opacity    = true,  -- blur behind transparent windows
            xray              = true,

            -- Texture & Quality
            noise      = 0.0217,
            contrast   = 0.8916,
            brightness = 0.8172,
            vibrancy   = 0.1696,

            -- Specifics
            popups = false,   -- whether to blur right-click menus/popups
        },

        -- screen_shader = home .. "/.config/hypr/shaders/grayscale_advanced.glsl"
    },
})

-- -------------------------------------------------------------------------------------------------
-- 3. ANIMATIONS
-- The active animation preset is sourced from the animations directory.
-- See: https://wiki.hypr.land/Configuring/Animations/
-- (Overridden in edit_here/source/appearance.lua to load the user's chosen preset)
-- -------------------------------------------------------------------------------------------------
dofile(os.getenv("HOME") .. "/.config/hypr/source/animations/active/active.lua")

-- -------------------------------------------------------------------------------------------------
-- 4. LAYOUTS
-- -------------------------------------------------------------------------------------------------
hl.config({
    dwindle = {
        preserve_split = true,
        -- smart_split   = false,
        -- smart_resizing = false,
    },
    master = {
        new_status = "master",
    },
})

-- -------------------------------------------------------------------------------------------------
-- 5. MISCELLANEOUS & PERFORMANCE
-- See: https://wiki.hypr.land/Configuring/Variables/#misc
-- -------------------------------------------------------------------------------------------------
hl.config({
    misc = {
        force_default_wallpaper  = 1,    -- set to 0 to enable the anime mascot
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
    },
})

-- -------------------------------------------------------------------------------------------------
-- 6. BINDS (Visual specific)
-- -------------------------------------------------------------------------------------------------
hl.config({
    binds = {
        allow_pin_fullscreen = true,
    },
})

-- -------------------------------------------------------------------------------------------------
-- 7. SMART GAPS (Single Window Override)
-- Applied automatically when only 1 window is tiled or fullscreened on a workspace.
-- -------------------------------------------------------------------------------------------------
local single_window_gap = 10
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = single_window_gap, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = single_window_gap, gaps_in = 0 })
