-- =============================================================================
-- INPUT — Base Configuration
-- =============================================================================
-- DO NOT EDIT THIS FILE.
-- Configure input in ~/.config/hypr/edit_here/source/input.lua
-- which is loaded last and overrides these defaults.
-- =============================================================================

-- -------------------------------------------------------------------------------------------------
-- 1. KEYBOARD & LANGUAGE
-- -------------------------------------------------------------------------------------------------
hl.config({
    input = {
        kb_layout  = "us",
        kb_options = "",       -- e.g. "caps:escape", "grp:alt_shift_toggle"

        resolve_binds_by_sym = false,
        numlock_by_default   = true,

        repeat_rate  = 35,    -- [10-100]
        repeat_delay = 250,   -- [100-1000]

        -- -----------------------------------------------------------------
        -- 2. MOUSE & POINTER ACCELERATION
        -- -----------------------------------------------------------------

        -- 0 = cursor movement doesn't change focus
        -- 1 = cursor movement changes focus (default)
        -- 2 = detached focus (click to focus keyboard, mouse follows independently)
        -- 3 = completely separate focus
        follow_mouse = 1,

        sensitivity   = 0,          -- [-1.0 to 1.0]
        accel_profile = "adaptive", -- flat | adaptive | custom
        force_no_accel = false,     -- "raw input" — bypasses most pointer settings
        left_handed    = false,
        mouse_refocus  = true,

        -- -----------------------------------------------------------------
        -- 3. SCROLLING & TRACKBALLS
        -- -----------------------------------------------------------------
        natural_scroll      = false,
        scroll_method       = "2fg",  -- 2fg | edge | on_button_down | no_scroll
        scroll_button       = 0,
        scroll_button_lock  = false,

        -- -----------------------------------------------------------------
        -- 4. TOUCHPAD
        -- -----------------------------------------------------------------
        touchpad = {
            natural_scroll      = true,
            disable_while_typing = true,
            tap_to_click        = true,
            clickfinger_behavior = false,
            drag_lock            = false,
        },
    },
})

-- -------------------------------------------------------------------------------------------------
-- 5. CURSOR BEHAVIOR & RENDERING
-- -------------------------------------------------------------------------------------------------
hl.config({
    cursor = {
        sync_gsettings_theme = true,

        -- 0 = HW cursors (performance)
        -- 1 = force SW cursors (compatibility / fixes disappearing cursor)
        -- 2 = auto (disable when tearing)
        no_hardware_cursors = 2,

        -- Nvidia specific optimization — 0 = off, 1 = on, 2 = auto
        use_cpu_buffer = 2,

        hide_on_key_press     = false,
        inactive_timeout      = 0,    -- hide cursor after X seconds (0 = never)

        -- 0 = disabled, 1 = move to center of focused window, 2 = force
        warp_on_change_workspace = 0,

        -- VRR-specific — 0 = off, 1 = on, 2 = auto
        no_break_fs_vrr = 2,

        zoom_factor = 1.0,    -- [1.0 - 5.0] magnifier zoom level
    },
})

-- -------------------------------------------------------------------------------------------------
-- 6. GESTURE PHYSICS (Tuning)
-- -------------------------------------------------------------------------------------------------
hl.config({
    gestures = {
        workspace_swipe_distance     = 300,
        workspace_swipe_cancel_ratio = 0.5,
        workspace_swipe_invert       = true,
        workspace_swipe_create_new   = true,
        workspace_swipe_forever      = false,
    },
})

-- -------------------------------------------------------------------------------------------------
-- 7. GESTURE BINDINGS
-- -------------------------------------------------------------------------------------------------

-- 3-finger up swipe → hyprexpo toggle
hl.gesture({ fingers = 3, direction = "up",    action = function() hl.exec_cmd("hyprctl dispatch hyprexpo:expo toggle") end })

-- 3-finger left swipe (unbound — customize in edit_here)
-- hl.gesture({ fingers = 3, direction = "left", action = function() end })

-- 3-finger down swipe → mute audio
hl.gesture({ fingers = 3, direction = "down",  action = function() hl.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")  end })

-- 3-finger right swipe → play/pause
hl.gesture({ fingers = 3, direction = "right", action = function() hl.exec_cmd("playerctl play-pause")                        end })

-- 4-finger horizontal → brightness
hl.gesture({ fingers = 4, direction = "left",  action = function() hl.exec_cmd("brightnessctl -e4 -n2 set 10%-")              end })
hl.gesture({ fingers = 4, direction = "right", action = function() hl.exec_cmd("brightnessctl -e4 -n2 set 10%+")              end })

-- 4-finger vertical → volume
hl.gesture({ fingers = 4, direction = "up",    action = function() hl.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 10%+") end })
hl.gesture({ fingers = 4, direction = "down",  action = function() hl.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-")         end })

-- 3-finger pinch → lock screen / screenshot
hl.gesture({ fingers = 3, direction = "pinchout", action = function() hl.exec_cmd("hyprlock --immediate")                                     end })
hl.gesture({ fingers = 3, direction = "pinchin",  action = function() hl.exec_cmd("slurp | grim -g - - | swappy -f -")                        end })
