-- DO NOT EDIT THIS FILE, if you want to configure something, edit the file
-- at this location. ~/.config/hypr/edit_here/source/

-- You can also use the TUI `Hypr Keybind Manager` from the rofi menu to change keybinds. It automatically
-- unbinds keybinds and checks for conflicts. 

-- -------------------------------------------------------------------------------------------------
-- HYPRLAND KEYBINDINGS
-- -------------------------------------------------------------------------------------------------

-- terminal    = "foot"
-- fileManager = "thunar"
-- menu        = "rofi -show drun"
-- browser     = "firefox"
-- textEditor  = "mousepad"
--
-- -- Path shortcut for cleaner config
--
--
-- -- -------------------------------------------------------------------------------------------------
-- -- 2. APPLICATION LAUNCHERS
-- -- -------------------------------------------------------------------------------------------------
--
-- hl.bind(
--     "SUPER + Q",
--     hl.dsp.exec_cmd(terminal),
--     { description = "Launch Terminal", submap_universal = true }
-- )
-- 
-- hl.bind(
--     "SUPER + W",
--     hl.dsp.exec_cmd(browser),
--     { description = "Launch Browser", submap_universal = true }
-- )
-- 
-- hl.bind(
--     "SUPER + E",
--     hl.dsp.exec_cmd(fileManager),
--     { description = "File Manager", submap_universal = true }
-- )
-- 
-- hl.bind(
--     "SUPER + R",
--     hl.dsp.exec_cmd(textEditor),
--     { description = "Open Text Editor", submap_universal = true }
-- )

hl.bind(
    "ALT + SPACE",
    hl.dsp.exec_cmd([[pkill rofi; rofi -show drun -run-command "{cmd}"]]),
    { description = "Launch Menu for Apps", submap_universal = true }
)

hl.bind(
    "CTRL + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/keybindings.sh"),
    { description = "Show Keybinds", submap_universal = true }
)

hl.bind(
    "SUPER + CTRL + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/emoji.sh"),
    { description = "Search Emojis", submap_universal = true }
)

hl.bind(
    "SUPER + CTRL + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/calculator.sh"),
    { description = "Calculator", submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/rofi_theme.sh"),
    { description = "Matugen Theme Config", submap_universal = true }
)

hl.bind(
    "CTRL + SPACE",
    hl.dsp.exec_cmd(dusky_scripts .. "images/wallpaper_selector.py"),
    { description = "Rofi Wallpaper Selector", submap_universal = true }
)

hl.bind(
    "SUPER + SPACE",
    hl.dsp.exec_cmd([[gdbus call --session --dest com.github.dusky.controlcenter --object-path /com/github/dusky/controlcenter --method org.freedesktop.Application.Activate "{}"]]),
    { description = "System Menu", submap_universal = true }
)

hl.bind(
    "CTRL + ALT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/dusky_glance.sh"),
    { description = "Dusky Glance", submap_universal = true }
)

-- Rofi Powermenu
hl.bind(
    "ALT + SHIFT + SPACE",
    hl.dsp.exec_cmd("pkill rofi; rofi -show power-menu -modi power-menu:" .. dusky_scripts .. "rofi/powermenu.sh"),
    { description = "Power Menu" }
)

-- System Monitor (btop)
hl.bind(
    "CTRL + SHIFT + escape",
    hl.dsp.exec_cmd(terminal .. " --class btop -e btop"),
    { description = "System Monitor", submap_universal = true }
)


-- -------------------------------------------------------------------------------------------------
-- 3. SYSTEM UTILITIES & TOGGLES
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "ALT + 1",
    hl.dsp.exec_cmd("foot --app-id=dusky_network.sh $HOME/user_scripts/network_manager/dusky_network.sh"),
    { description = "Wi-Fi Manager" }
)

hl.bind(
    "ALT + 2",
    hl.dsp.exec_cmd("blueman-manager"),
    { description = "Bluetooth Manager" }
)

hl.bind(
    "ALT + 3",
    hl.dsp.exec_cmd("pavucontrol"),
    { description = "Audio Mixer" }
)

hl.bind(
    "ALT + 4",
    hl.dsp.exec_cmd(dusky_scripts .. "images/wallpaper_selector.py"),
    { description = "Dusky Wallpaper Selector", submap_universal = true }
)

hl.bind(
    "SUPER + apostrophe",
    hl.dsp.exec_cmd(dusky_scripts .. "theme_matugen/theme_ctl.sh next"),
    { description = "Cycle Next Wallpaper", submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + apostrophe",
    hl.dsp.exec_cmd(dusky_scripts .. "rofi/rofi_wallpaper_selctor.sh --next-fav"),
    { description = "Cycle Fav Wallpaper", submap_universal = true }
)

hl.bind(
    "ALT + 5",
    hl.dsp.exec_cmd(terminal .. " -e " .. dusky_scripts .. "drives/drive_manager.sh unlock browser"),
    { description = "Unlock Browser" }
)

hl.bind(
    "ALT + SHIFT + 5",
    hl.dsp.exec_cmd(terminal .. " -e " .. dusky_scripts .. "drives/drive_manager.sh lock browser"),
    { description = "Lock Browser", locked = true }
)


-- --- Passthrough (Disable keybinds) ---
-- ⚠ Requires Hyprland built after May 29 2026 (PR #14856)

local SUBMAP_MANUAL_PT = "keybinds_disabled"  -- NOT "passthrough" (reserved dispatcher name)

hl.bind(
    "ALT + 6",
    function()
        hl.notification.create({ text = "Passthrough Enabled - Press ALT+6 to exit", timeout = 3000 })
        hl.dispatch(hl.dsp.submap(SUBMAP_MANUAL_PT))
    end,
    { description = "Enable Game Mode (Disable Keybinds)", locked = true }
)

hl.define_submap(SUBMAP_MANUAL_PT, function()
    hl.bind(
        "ALT + 6",   -- ← same key now works with the #14856 fix
        function()
            hl.notification.create({ text = "Passthrough Disabled - Keybinds restored", timeout = 2000 })
            hl.dispatch(hl.dsp.submap("reset"))
        end,
        { description = "Disable Game Mode (Restore Keybinds)", locked = true }
    )
end)


hl.bind(
    "CTRL + ALT + R",
    hl.dsp.exec_cmd(dusky_scripts .. "hypr/monitor/screen_rotate.py -90"),
    { description = "Rotate Screen Clockwise", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "CTRL + ALT + SHIFT + R",
    hl.dsp.exec_cmd(dusky_scripts .. "hypr/monitor/screen_rotate.py +90"),
    { description = "Rotate Screen Anti-Clockwise", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "ALT + F7",
    function()
        hl.timer(function()
            hl.dispatch(hl.dsp.dpms({ action = "disable" }))
        end, { timeout = 500, type = "oneshot" })
    end,
    { description = "Screen Off DPMS", locked = true, submap_universal = true }
)

hl.bind(
    "ALT + F8",
    function()
        hl.timer(function()
            hl.dispatch(hl.dsp.dpms({ action = "enable" }))
        end, { timeout = 500, type = "oneshot" })
    end,
    { description = "Screen On DPMS", locked = true, submap_universal = true }
)



-- --- Waybar Toggle ---
hl.bind(
    "ALT + 9",
    hl.dsp.exec_cmd(dusky_scripts .. "waybar/waybar_toggle.sh"),
    { description = "Start Waybar for 1 Min", submap_universal = true }
)

hl.bind(
    "ALT + 0",
    hl.dsp.exec_cmd("pkill tray-tui; foot --app-id=dusky_tui tray-tui"),
    { description = "system Tray TUI", submap_universal = true }
)

hl.bind(
    "SUPER + ALT + W",
    hl.dsp.exec_cmd(dusky_scripts .. "waybar/dusky_waybars.sh --toggle"),
    { description = "Waybar Swap Configs", submap_universal = true }
)

hl.bind(
    "SUPER + ALT + SHIFT + W",
    hl.dsp.exec_cmd(dusky_scripts .. "waybar/dusky_waybars.sh --back_toggle"),
    { description = "Waybar Swap Configs", submap_universal = true }
)


-- --- Utilities ---
hl.bind(
    "ALT + F4",
    hl.dsp.exec_cmd(dusky_scripts .. "wlogout/wlogout_scale.sh"),
    { description = "Logout Menu" }
)

hl.bind(
    "SUPER + SHIFT + R",
    hl.dsp.exec_cmd("hyprctl reload"),
    { description = "Reload Hyprland", locked = true }
)

hl.bind(
    "ALT + V",
    hl.dsp.exec_cmd([[gdbus call --session --dest org.dusky.quickpanal --object-path /org/dusky/quickpanal --method org.freedesktop.Application.Activate "{}"]]),
    { description = "Dusky QuickPanal" }
)

hl.bind(
    "SUPER + F",
    hl.dsp.exec_cmd(dusky_scripts .. "hypr/monitor/adjust_scale.py +"),
    { description = "Scale Up", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + F",
    hl.dsp.exec_cmd(dusky_scripts .. "hypr/monitor/adjust_scale.py -"),
    { description = "Scale Down", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + semicolon",
    hl.dsp.exec_cmd(terminal .. " --class performance.sh -e " .. dusky_scripts .. "performance/services_and_process_terminator.sh"),
    { description = "Kill Process", submap_universal = true }
)

-- --- Wayclick & OSD Key Presses ---
hl.bind(
    "SUPER + U",
    hl.dsp.exec_cmd(dusky_scripts .. "wayclick/dusky_wayclick.sh"),
    { description = "Key Press Sound", submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + U",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/dusky_keys/dusky_keys.sh"),
    { description = "OSD KEY Presses", submap_universal = true }
)

-- --- Hyprshade (Visual Filters) ---
hl.bind(
    "SUPER + ALT + S",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/shader_menu.sh"),
    { description = "Shader Menu", submap_universal = true }
)

hl.bind(
    "SUPER + ALT + X",
    hl.dsp.exec_cmd("hyprshade off"),
    { description = "Disable Shader", locked = true, submap_universal = true }
)

hl.bind(
    "SUPER + ALT + V",
    hl.dsp.exec_cmd("hyprshade on vibrance"),
    { description = "Vibrant Shader", locked = true, submap_universal = true }
)

-- --- Hyprland Animations ---
hl.bind(
    "SUPER + ALT + A",
    hl.dsp.exec_cmd("pkill rofi; rofi -show animations -modi \"animations:" .. dusky_scripts .. "rofi/hypr_anim.sh\""),
    { description = "Hyprland Animation Rofi Menu", submap_universal = true }
)

-- --- Special Workspace (Spotify) ---
hl.bind(
    "SUPER + SHIFT + M",
    hl.dsp.exec_cmd(dusky_scripts .. "spotify/spotify_toggle.sh"),
    { description = "Special Workspace for Spotify", submap_universal = true }
)


-- --- Opacity & Blur Toggles ---
hl.bind(
    "SUPER + ALT + period",
    hl.dsp.exec_cmd(dusky_scripts .. "hypr/hypr_blur_opacity_shadow_toggle.sh"),
    { description = "Toggle Blur/Opacity", locked = true, submap_universal = true }
)

hl.bind(
    "SUPER + period",
    hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "activewindow" }),
    { description = "Toggle Opacity", locked = true, submap_universal = true }
)

hl.bind(
    "SUPER + comma",
    hl.dsp.window.set_prop({ prop = "no_blur", value = "toggle", window = "activewindow" }),
    { description = "Toggle Per-Window Blur", locked = true, submap_universal = true }
)


-- --- Accessibility: Zoom ---
hl.config({ cursor = { zoom_disable_aa = true } })

hl.bind(
    "SUPER + equal",
    function()
        local z = hl.get_config("cursor.zoom_factor")
        hl.config({ cursor = { zoom_factor = z * 1.25 } })
    end,
    { description = "Zoom In", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + minus",
    function()
        local z = hl.get_config("cursor.zoom_factor")
        local nz = z / 1.25
        if nz < 1.0 then nz = 1.0 end
        hl.config({ cursor = { zoom_factor = nz } })
    end,
    { description = "Zoom Out", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + BACKSPACE",
    function()
        hl.config({ cursor = { zoom_factor = 1.0 } })
    end,
    { description = "Reset Zoom", locked = true, submap_universal = true }
)


-- --- Clipboard & Screenshot ---
-- hl.bind(
--     "SUPER + V",
--     hl.dsp.exec_cmd("pkill rofi; rofi -modi \"clipboard:" .. dusky_scripts .. "rofi/rofi_cliphist.sh\" -show clipboard"),
--     { description = "Clipboard History" }
-- )

hl.bind("SUPER + V", function()
    -- Kill any existing clipboard foot instance with SIGTERM (-15).
    -- The '^foot' anchor is critical: it means only processes whose
    -- cmdline STARTS with 'foot' are matched. The sh subprocess spawned
    -- by os.execute starts with 'sh', so it can never self-match.
    -- This eliminates the self-terminating sh -c wrapper bug.
    os.execute("pkill -15 -f '^foot.*terminal_clipboard'")

    -- Dispatch the fresh instance. hl.dispatch + exec_cmd spawns
    -- foot directly without a sh -c wrapper, so there are no shell
    -- chain issues here. os.getenv() expands $HOME safely in Lua.
    hl.dispatch(hl.dsp.exec_cmd(
        "foot --app-id=terminal_clipboard.sh " ..
        os.getenv("HOME") .. "/user_scripts/clipboard/terminal_clipboard.sh"
    ))
end, { description = "Clipboard History", submap_universal = true })


hl.bind(
    "SUPER + B",
    hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"),
    { description = "Color Picker", submap_universal = true }
)

hl.bind(
    "SUPER + S",
    hl.dsp.exec_cmd(dusky_scripts .. "images/dusky_screenshot.sh --region --freeze --no-notify"),
    { description = "Quick Screenshot", submap_universal = true }
)

hl.bind(
    "SHIFT + Print",
    hl.dsp.exec_cmd([[grim - | wl-copy && notify-send "Fullscreen Screenshot in Clipboard"]]),
    { description = "Full Screen Quick Screenshot", locked = true, submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + S",
    hl.dsp.exec_cmd(dusky_scripts .. "images/dusky_screenshot.sh --region --freeze --annotate --no-notify --tool arrow"),
    { description = "Screenshot and Annotation", submap_universal = true }
)

hl.bind(
    "Print",
    hl.dsp.exec_cmd("pgrep -x swappy || (grim - | satty -f -)"),
    { description = "Fullscreen Screenshot and Annotation", submap_universal = true }
)

hl.bind(
    "SHIFT + CTRL + ALT + space",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/dusky_rofi_screenshot.sh"),
    { description = "Dusky Screenshoter", submap_universal = true }
)


-- --- Screen Recorder ---
hl.bind(
    "ALT + R",
    hl.dsp.exec_cmd(dusky_scripts .. "dusky_recorder/dusky_recorder.sh"),
    { description = "Screen Recorder" }
)


-- --- AI & Voice Tools ---

-- Google Image Search
hl.bind(
    "SUPER + G",
    hl.dsp.exec_cmd(dusky_scripts .. "google_image_search/google_image_search.sh"),
    { description = "Image Search (Select and search)", submap_universal = true }
)

-- OCR (Tesseract)
hl.bind(
    "SUPER + T",
    hl.dsp.exec_cmd("pgrep tesseract || (slurp | grim -g - - | tesseract stdin stdout -l eng | wl-copy)"),
    { description = "OCR Selection", submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + T",
    hl.dsp.exec_cmd("grim - | tesseract stdin stdout -l eng | wl-copy"),
    { description = "OCR Fullscreen", submap_universal = true }
)

-- ollama Sidebar
hl.bind(
    "SUPER + ALT + O",
    hl.dsp.exec_cmd(terminal .. " --class ollama_terminal.sh -e " .. dusky_scripts .. "llm/ollama_terminal.sh"),
    { description = "AI LLM Ollama Chat", submap_universal = true }
)

-- Music Recognition
hl.bind(
    "SUPER + ALT + M",
    hl.dsp.exec_cmd(terminal .. " --hold  " .. dusky_scripts .. "music/music_recognition.sh"),
    { description = "Music Recognition aka Shazam", submap_universal = true }
)

-- Kokoro TTS
hl.bind(
    "SUPER + O",
    hl.dsp.exec_cmd("wl-copy \"$(wl-paste -p)\" && " .. dusky_scripts .. "tts_stt/dusky_kokoro/trigger.sh"),
    { description = "TTS Kokoro GPU", submap_universal = true }
)

-- Kokoro TTS - VC Routed
hl.bind(
    "SUPER + SHIFT + O",
    hl.dsp.exec_cmd(dusky_scripts .. "audio/router/TTS_VC.sh"),
    { description = "TTS VC", submap_universal = true }
)

-- NVIDIA Parakeet
hl.bind(
    "SUPER + I",
    hl.dsp.exec_cmd(dusky_scripts .. "tts_stt/dusky_parakeet/trigger.sh"),
    { description = "STT Parakeet GPU", submap_universal = true }
)

-- FasterWhisper STT
-- hl.bind(
--     "SUPER + SHIFT + I",
--     hl.dsp.exec_cmd(dusky_scripts .. "tts_stt/faster_whisper/faster_whisper_stt.sh"),
--     { description = "STT Whisper CPU", submap_universal = true }
-- )


-- ======================================
-- NOTIFICATION ACTIONS (MAKO + ROFI)
-- ======================================

-- --- Notification Panel ---
hl.bind(
    "SUPER + N",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "rofi/rofi_mako.sh"),
    { description = "Notification History", submap_universal = true }
)

-- --- mako Clear all screen notifications ---
hl.bind(
    "SUPER + ALT + D",
    hl.dsp.exec_cmd("makoctl dismiss -a"),
    { description = "Clear Screen Notifications", locked = true, submap_universal = true }
)

hl.bind(
    "SUPER + ALT + F",
    hl.dsp.exec_cmd([[makoctl menu -- rofi -dmenu -p "Action: "]]),
    { description = "Interact with the current notification (answer Yes/No prompts)", submap_universal = true }
)

-- --- Screen Lock ---
hl.bind(
    "SUPER + M",
    hl.dsp.exec_cmd(dusky_scripts .. "hyprlock/lock.sh"),
    { description = "Lock Screen", submap_universal = true }
)


-- -------------------------------------------------------------------------------------------------
-- 4. WINDOW MANAGEMENT
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "SUPER + C",
    hl.dsp.window.close(),
    { description = "Close Window", submap_universal = true }
)

-- ----
-- Bind this at your own risk (In Beta)
-- ----
--
-- /user_scripts/tools/workspace/close-workspace.sh -- Working Feature but Unsure
-- hl.bind(
--     "SUPER + SHIFT + C",
--     hl.dsp.exec_cmd(dusky_scripts .. "tools/workspace/close-workspace.sh"),
--     { description = "Close Workspace", submap_universal = true }
-- )
-- ----
-- /user_scripts/tools/workspace/safety-close.sh -- Working Feature but Unsure
-- hl.bind(
--     "SUPER + SHIFT + B",
--     hl.dsp.exec_cmd(dusky_scripts .. "tools/workspace/safety-close.sh"),
--     { description = "Safety Close Window", submap_universal = true }
-- )
-- ----

hl.bind(
    "SUPER + A",
    hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }),
    { description = "Window Fullscreen", submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + A",
    hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }),
    { description = "Window Maximize", submap_universal = true }
)

hl.bind(
    "SUPER + X",
    hl.dsp.window.pin(),
    { description = "Pin Window", submap_universal = true }
)

--------------------------------------------------------------------
-- Split requiers preserve_split to be true managed in another config
--------------------------------------------------------------------
-- hl.config({
--     dwindle = {
--         preserve_split = true,
--     },
-- })

hl.bind(
    "SUPER + Y",
    hl.dsp.layout("togglesplit"),
    { description = "Toggle Window Split", submap_universal = true }
)
---------------------------------------------
hl.bind(
    "SUPER + D",
    hl.dsp.exec_cmd([[
        if hyprctl activewindow | grep -q 'floating: 0'; then
            W=$(hyprctl monitors -j | jq '.[] | select(.focused) | ((.width / .scale) * 0.9) | floor')
            H=$(hyprctl monitors -j | jq '.[] | select(.focused) | ((.height / .scale) * 0.9) | floor')
            hyprctl --batch "dispatch hl.dsp.window.float({action='set'}); dispatch hl.dsp.window.resize({x=${W}, y=${H}, relative=false})"
            hyprctl dispatch "hl.dsp.window.center()"
        else
            hyprctl dispatch "hl.dsp.window.float({action='unset'})"
        fi
    ]]),
    { description = "Smart Float", submap_universal = true }
)


hl.bind(
    "SUPER + SHIFT + D",
    hl.dsp.window.pseudo({ action = "toggle" }),
    { description = "Toggle Pseudo", submap_universal = true }
)


-- --- Focus Movement ---
hl.bind(
    "SUPER + h",
    hl.dsp.focus({ direction = "l" }),
    { description = "Focus Left", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + l",
    hl.dsp.focus({ direction = "r" }),
    { description = "Focus Right", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + k",
    hl.dsp.focus({ direction = "u" }),
    { description = "Focus Up", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + j",
    hl.dsp.focus({ direction = "d" }),
    { description = "Focus Down", repeating = true, submap_universal = true }
)


-- --- Window Movement ---
hl.bind(
    "SUPER + SHIFT + h",
    hl.dsp.window.move({ direction = "l" }),
    { description = "Move Left", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + l",
    hl.dsp.window.move({ direction = "r" }),
    { description = "Move Right", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + k",
    hl.dsp.window.move({ direction = "u" }),
    { description = "Move Up", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + j",
    hl.dsp.window.move({ direction = "d" }),
    { description = "Move Down", repeating = true, submap_universal = true }
)


-- --- Window Resizing ---
hl.bind(
    "SUPER + right",
    hl.dsp.window.resize({ x = 30, y = 0, relative = true }),
    { description = "Resize Width +", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + left",
    hl.dsp.window.resize({ x = -30, y = 0, relative = true }),
    { description = "Resize Width -", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + up",
    hl.dsp.window.resize({ x = 0, y = -30, relative = true }),
    { description = "Resize Height -", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + down",
    hl.dsp.window.resize({ x = 0, y = 30, relative = true }),
    { description = "Resize Height +", repeating = true, submap_universal = true }
)


-- -------------------------------------------------------------------------------------------------
-- 5. WORKSPACE MANAGEMENT
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "SUPER + TAB",
    hl.dsp.focus({ workspace = "previous" }),
    { description = "Last Workspace", repeating = true, submap_universal = true }
)

hl.bind(
    "ALT + SHIFT + TAB",
    hl.dsp.focus({ workspace = "e-1" }),
    { description = "Cycle Backward", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + TAB",
    hl.dsp.focus({ workspace = "e+1" }),
    { description = "Cycle Next WS", repeating = true, submap_universal = true }
)

hl.bind(
    "SUPER + mouse_down",
    hl.dsp.focus({ workspace = "e+1" }),
    { description = "Cycle Next Workspace", submap_universal = true }
)

hl.bind(
    "SUPER + mouse_up",
    hl.dsp.focus({ workspace = "e-1" }),
    { description = "Cycle Previous Workspace", submap_universal = true }
)

hl.bind(
    "SUPER + Z",
    hl.dsp.workspace.toggle_special("magic"),
    { description = "Toggle Scratchpad",submap_universal = true }
)

hl.bind(
    "SUPER + SHIFT + Z",
    hl.dsp.window.move({ workspace = "special:magic" }),
    { description = "Move to Scratchpad", submap_universal = true }
)


------------------------------------------------------
-- SINGLE MONITOR
-----------------------------------------------------


-- -- Explicitly Unrolled Workspaces
-- 
-- -- Focus Workspace 
-- hl.bind(
--     "SUPER + 1",
--     hl.dsp.focus({ workspace = "1" }),
--     { description = "Switch To Workspace 1", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 2",
--     hl.dsp.focus({ workspace = "2" }),
--     { description = "Switch To Workspace 2", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 3",
--     hl.dsp.focus({ workspace = "3" }),
--     { description = "Switch To Workspace 3", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 4",
--     hl.dsp.focus({ workspace = "4" }),
--     { description = "Switch To Workspace 4", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 5",
--     hl.dsp.focus({ workspace = "5" }),
--     { description = "Switch To Workspace 5", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 6",
--     hl.dsp.focus({ workspace = "6" }),
--     { description = "Switch To Workspace 6", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 7",
--     hl.dsp.focus({ workspace = "7" }),
--     { description = "Switch To Workspace 7", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 8",
--     hl.dsp.focus({ workspace = "8" }),
--     { description = "Switch To Workspace 8", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 9",
--     hl.dsp.focus({ workspace = "9" }),
--     { description = "Switch To Workspace 9", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + 0",
--     hl.dsp.focus({ workspace = "10" }),
--     { description = "Switch To Workspace 10", submap_universal = true }
-- )
-- 
-- -- Move Window to Workspace
-- hl.bind(
--     "SUPER + SHIFT + 1",
--     hl.dsp.window.move({ workspace = "1" }),
--     { description = "Move To Workspace 1", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 2",
--     hl.dsp.window.move({ workspace = "2" }),
--     { description = "Move To Workspace 2", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 3",
--     hl.dsp.window.move({ workspace = "3" }),
--     { description = "Move To Workspace 3", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 4",
--     hl.dsp.window.move({ workspace = "4" }),
--     { description = "Move To Workspace 4", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 5",
--     hl.dsp.window.move({ workspace = "5" }),
--     { description = "Move To Workspace 5", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 6",
--     hl.dsp.window.move({ workspace = "6" }),
--     { description = "Move To Workspace 6", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 7",
--     hl.dsp.window.move({ workspace = "7" }),
--     { description = "Move To Workspace 7", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 8",
--     hl.dsp.window.move({ workspace = "8" }),
--     { description = "Move To Workspace 8", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 9",
--     hl.dsp.window.move({ workspace = "9" }),
--     { description = "Move To Workspace 9", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + SHIFT + 0",
--     hl.dsp.window.move({ workspace = "10" }),
--     { description = "Move To Workspace 10", submap_universal = true }
-- )
-- 
-- -- Move Window Silently to Workspace
-- hl.bind(
--     "SUPER + ALT + 1",
--     hl.dsp.window.move({ workspace = "1", follow = false }),
--     { description = "Move Silently To Workspace 1", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 2",
--     hl.dsp.window.move({ workspace = "2", follow = false }),
--     { description = "Move Silently To Workspace 2", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 3",
--     hl.dsp.window.move({ workspace = "3", follow = false }),
--     { description = "Move Silently To Workspace 3", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 4",
--     hl.dsp.window.move({ workspace = "4", follow = false }),
--     { description = "Move Silently To Workspace 4", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 5",
--     hl.dsp.window.move({ workspace = "5", follow = false }),
--     { description = "Move Silently To Workspace 5", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 6",
--     hl.dsp.window.move({ workspace = "6", follow = false }),
--     { description = "Move Silently To Workspace 6", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 7",
--     hl.dsp.window.move({ workspace = "7", follow = false }),
--     { description = "Move Silently To Workspace 7", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 8",
--     hl.dsp.window.move({ workspace = "8", follow = false }),
--     { description = "Move Silently To Workspace 8", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 9",
--     hl.dsp.window.move({ workspace = "9", follow = false }),
--     { description = "Move Silently To Workspace 9", submap_universal = true }
-- )
-- hl.bind(
--     "SUPER + ALT + 0",
--     hl.dsp.window.move({ workspace = "10", follow = false }),
--     { description = "Move Silently To Workspace 10", submap_universal = true }
-- )


------------------------------------------------------
-- Multi MONITOR
-----------------------------------------------------

-- Each monitor gets its own "bank" of 10 workspaces, assigned left-to-right
-- by X position. SUPER+1 always means "workspace 1 on THIS monitor".
--   Monitor 0 (leftmost) → workspaces  1–10
--   Monitor 1            → workspaces 11–20
--   …etc.
--
-- The script handles all the math; these binds just pass the 1-10 slot number.
-- -------------------------------------------------------------------------------------------------

local ws_script = dusky_scripts .. "hypr/multi_monitor_workspace.sh"

-- Helper shorthand so the repeated hl.dsp.exec_cmd calls stay readable
local function ws(action, n)
    return hl.dsp.exec_cmd(ws_script .. " " .. action .. " " .. tostring(n))
end

-- ── Switch to Workspace (Context Relative) ────────────────────────────────────

hl.bind("SUPER + 1", ws("workspace", 1),  { description = "Switch To Context 1", submap_universal = true })
hl.bind("SUPER + 2", ws("workspace", 2),  { description = "Switch To Context 2", submap_universal = true })
hl.bind("SUPER + 3", ws("workspace", 3),  { description = "Switch To Context 3", submap_universal = true })
hl.bind("SUPER + 4", ws("workspace", 4),  { description = "Switch To Context 4", submap_universal = true })
hl.bind("SUPER + 5", ws("workspace", 5),  { description = "Switch To Context 5", submap_universal = true })
hl.bind("SUPER + 6", ws("workspace", 6),  { description = "Switch To Context 6", submap_universal = true })
hl.bind("SUPER + 7", ws("workspace", 7),  { description = "Switch To Context 7", submap_universal = true })
hl.bind("SUPER + 8", ws("workspace", 8),  { description = "Switch To Context 8", submap_universal = true })
hl.bind("SUPER + 9", ws("workspace", 9),  { description = "Switch To Context 9", submap_universal = true })
hl.bind("SUPER + 0", ws("workspace", 10), { description = "Switch To Context 10", submap_universal = true })

-- ── Move Active Window to Workspace (Context Relative) ───────────────────────

hl.bind("SUPER + SHIFT + 1", ws("movetoworkspace", 1),  { description = "Move To Context 1", submap_universal = true })
hl.bind("SUPER + SHIFT + 2", ws("movetoworkspace", 2),  { description = "Move To Context 2", submap_universal = true })
hl.bind("SUPER + SHIFT + 3", ws("movetoworkspace", 3),  { description = "Move To Context 3", submap_universal = true })
hl.bind("SUPER + SHIFT + 4", ws("movetoworkspace", 4),  { description = "Move To Context 4", submap_universal = true })
hl.bind("SUPER + SHIFT + 5", ws("movetoworkspace", 5),  { description = "Move To Context 5", submap_universal = true })
hl.bind("SUPER + SHIFT + 6", ws("movetoworkspace", 6),  { description = "Move To Context 6", submap_universal = true })
hl.bind("SUPER + SHIFT + 7", ws("movetoworkspace", 7),  { description = "Move To Context 7", submap_universal = true })
hl.bind("SUPER + SHIFT + 8", ws("movetoworkspace", 8),  { description = "Move To Context 8", submap_universal = true })
hl.bind("SUPER + SHIFT + 9", ws("movetoworkspace", 9),  { description = "Move To Context 9", submap_universal = true })
hl.bind("SUPER + SHIFT + 0", ws("movetoworkspace", 10), { description = "Move To Context 10", submap_universal = true })

-- ── Move Window Silently (Context Relative) ───────────────────────────────────

hl.bind("SUPER + ALT + 1", ws("movetoworkspacesilent", 1),  { description = "Silent Move To Context 1", submap_universal = true })
hl.bind("SUPER + ALT + 2", ws("movetoworkspacesilent", 2),  { description = "Silent Move To Context 2", submap_universal = true })
hl.bind("SUPER + ALT + 3", ws("movetoworkspacesilent", 3),  { description = "Silent Move To Context 3", submap_universal = true })
hl.bind("SUPER + ALT + 4", ws("movetoworkspacesilent", 4),  { description = "Silent Move To Context 4", submap_universal = true })
hl.bind("SUPER + ALT + 5", ws("movetoworkspacesilent", 5),  { description = "Silent Move To Context 5", submap_universal = true })
hl.bind("SUPER + ALT + 6", ws("movetoworkspacesilent", 6),  { description = "Silent Move To Context 6", submap_universal = true })
hl.bind("SUPER + ALT + 7", ws("movetoworkspacesilent", 7),  { description = "Silent Move To Context 7", submap_universal = true })
hl.bind("SUPER + ALT + 8", ws("movetoworkspacesilent", 8),  { description = "Silent Move To Context 8", submap_universal = true })
hl.bind("SUPER + ALT + 9", ws("movetoworkspacesilent", 9),  { description = "Silent Move To Context 9", submap_universal = true })
hl.bind("SUPER + ALT + 0", ws("movetoworkspacesilent", 10), { description = "Silent Move To Context 10", submap_universal = true })


-- -------------------------------------------------------------------------------------------------
-- 6. MOUSE BINDINGS
-- -------------------------------------------------------------------------------------------------

hl.bind(
    "SUPER + mouse:272",
    hl.dsp.window.drag(),
    { description = "Move Window", mouse = true, submap_universal = true }
)

hl.bind(
    "SUPER + mouse:273",
    hl.dsp.window.resize(),
    { description = "Resize Window", mouse = true, submap_universal = true }
)


-- -------------------------------------------------------------------------------------------------
-- 7. HARDWARE & MEDIA KEYS
-- -------------------------------------------------------------------------------------------------

-- Standard Media Keys (Repeatable via 'e' flag, Lockscreen bypass via 'l')
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --vol-up 5"),
    { description = "Volume up", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --vol-down 5"),
    { description = "Volume down", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --vol-mute"),
    { description = "Mute", locked = true, submap_universal = true }
)

hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --mic-mute"),
    { description = "Mute microphone", locked = true, submap_universal = true }
)

hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --bright-up 5"),
    { description = "Brightness up", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --bright-down 5"),
    { description = "Brightness down", locked = true, repeating = true, submap_universal = true }
)

-- Precise Adjustments (Alt Modifier)
hl.bind(
    "ALT + XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --vol-up 1"),
    { description = "Volume up precise", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "ALT + XF86AudioLowerVolume",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --vol-down 1"),
    { description = "Volume down precise", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "ALT + XF86MonBrightnessUp",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --bright-up 1"),
    { description = "Brightness up precise", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "ALT + XF86MonBrightnessDown",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --bright-down 1"),
    { description = "Brightness down precise", locked = true, repeating = true, submap_universal = true }
)

-- Keyboard Backlight
hl.bind(
    "XF86KbdBrightnessUp",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --kbd-bright-up 10"),
    { description = "Keyboard Brightness up", locked = true, repeating = true, submap_universal = true }
)

hl.bind(
    "XF86KbdBrightnessDown",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --kbd-bright-down 10"),
    { description = "Keyboard Brightness down", locked = true, repeating = true, submap_universal = true }
)

-- Player Controls (Routed through script for OSD feedback)
hl.bind(
    "XF86AudioNext",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --next"),
    { description = "Next track", locked = true, submap_universal = true }
)

hl.bind(
    "XF86AudioPrev",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --prev"),
    { description = "Previous track", locked = true, submap_universal = true }
)

hl.bind(
    "XF86AudioPlay",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --play-pause"),
    { description = "Play", locked = true, submap_universal = true }
)

hl.bind(
    "XF86AudioPause",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --play-pause"),
    { description = "Pause", locked = true, submap_universal = true }
)

hl.bind(
    "XF86AudioStop",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --stop"),
    { description = "Stop", locked = true, submap_universal = true }
)

hl.bind(
    "SUPER + P",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --play-pause"),
    { description = "Toggle Pause", locked = true, submap_universal = true }
)

-- Custom Audio/Mic Switching Scripts
hl.bind(
    "ALT + P",
    hl.dsp.exec_cmd(dusky_scripts .. "mako_osd/osd_router/osd_router.sh --vol-mute"),
    { description = "Mute Audio", locked = true }
)

-- Mono Audio toggle
hl.bind(
    "ALT + M",
    hl.dsp.exec_cmd(dusky_scripts .. "audio/mono_audio_pipewire.py"),
    { description = "Mono Audio Toggle", locked = true }
)

-- Audio/Mic Switching
hl.bind(
    "ALT + O",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "audio/dusky_output.sh"),
    { description = "Switch Audio Output", locked = true }
)

hl.bind(
    "ALT + I",
    hl.dsp.exec_cmd("pkill rofi; " .. dusky_scripts .. "audio/dusky_input.sh"),
    { description = "Switch Mic Input", locked = true }
)

-- Calculator
hl.bind(
    "XF86Calculator",
    hl.dsp.exec_cmd("gnome-calculator"),
    { description = "Calculator", submap_universal = true }
)



-- =============================================================================
--  APP KEY PASSTHROUGH
--  ──────────────────────────────────────────────────────────────────────────
--  Some apps (TUIs, clipboard tools, etc.) need full keyboard access.
--  When one of these apps is focused, Hyprland silences its own keybinds
--  and lets every keystroke pass directly to the app.
--
--  Your normal keybinds that use { submap_universal = true } still work.
--  Everything else is intentionally silenced while these apps are focused.
--
--  HOW TO ADD AN APP:
--    1. Focus the app, then run: hyprctl activewindow | grep class
--    2. Add the class name to the table below.
-- =============================================================================

local PASSTHROUGH_APPS = {
    ["terminal_clipboard.sh"] = true,
    ["dusky_tui"]             = true,
    ["wallpaper_selector.py"] = true,
    ["virt-manager"]          = true,
    -- ["foot_vim"]           = true,   ← add more here, same format
}

-- The name of our custom submap.
-- Referenced in multiple places, so we keep it as a variable
-- to avoid typos and make renaming easy.
local SUBMAP_PASSTHROUGH = "app_passthrough"


-- =============================================================================
--  THE PASSTHROUGH SUBMAP DEFINITION
--  ──────────────────────────────────────────────────────────────────────────
--  This submap is intentionally empty of binds.
--  Its whole job is to be a "silent mode" — when active, Hyprland stops
--  intercepting keys, so your focused app receives them instead.
--
--  Your essential binds (terminal, launcher, workspace switching, etc.)
--  should use { submap_universal = true } in your main keybinds.lua so
--  they continue to work even while this submap is active.
--
--  The only bind defined here is the emergency manual escape hatch.
-- =============================================================================

hl.define_submap(SUBMAP_PASSTHROUGH, function()

    -- ─── Emergency manual reset ───────────────────────────────────────────────
    -- If something goes wrong and you're stuck (e.g. no window is focused),
    -- press SUPER+Escape at any time to force-return to your normal keybinds.
    -- locked = true ensures this works even on the lock screen.
    hl.bind("SUPER + Escape", hl.dsp.submap("reset"), { locked = true, submap_universal = true })

    -- ─── Add app-specific binds below if needed ───────────────────────────────
    -- If a passthrough app still needs SOME Hyprland bind to work (beyond your
    -- universal ones), define it here. Otherwise leave this section empty.
    --
    -- hl.bind("SUPER + N", hl.dsp.exec_cmd("..."))

end)


-- =============================================================================
--  AUTOMATIC SUBMAP SWITCHING
--  ──────────────────────────────────────────────────────────────────────────
--  Three listeners together make this bulletproof:
--
--  [1] hyprland.start  → guarantees we start in global on boot, even if a
--                         passthrough app launches and grabs focus early.
--
--  [2] window.active   → switches mode whenever focus changes between windows.
--                         Enters passthrough when a listed app is focused;
--                         resets to global for everything else.
--
--  [3] window.destroy  → catches the case where a passthrough app closes but
--                         focus goes to nothing (no window). In that situation
--                         window.active doesn't fire, leaving you stuck in
--                         passthrough. This listener catches that gap.
-- =============================================================================

-- [1] Always start in the global submap, no matter what.
hl.on("hyprland.start", function()
    hl.dispatch(hl.dsp.submap("reset"))
end)

-- [2] Switch submap whenever the focused window changes.
hl.on("window.active", function(w)
    if w ~= nil and PASSTHROUGH_APPS[w.class] then
        hl.dispatch(hl.dsp.submap(SUBMAP_PASSTHROUGH))  -- silence Hyprland binds
    else
        hl.dispatch(hl.dsp.submap("reset"))              -- restore normal binds
    end
end)

-- [3] If a passthrough app is closed and nothing else takes focus,
--     window.active won't fire. This ensures we still reset.
hl.on("window.destroy", function(w)
    if w ~= nil and PASSTHROUGH_APPS[w.class] then
        hl.dispatch(hl.dsp.submap("reset"))
    end
end)
