-- =============================================================================
-- KEYBINDINGS
-- =============================================================================
-- DO NOT EDIT THIS FILE.
-- Add or override keybinds in ~/.config/hypr/edit_here/source/keybinds.lua
--
-- Application launcher binds (SUPER+Q/W/E/R) are intentionally left to the
-- user's edit_here file, so they can pick their preferred apps.
-- =============================================================================

local mainMod = "SUPER"
local home    = os.getenv("HOME")
local scripts = home .. "/user_scripts"

-- Accessibility: enable anti-aliasing bypass for cursor zoom
hl.config({ cursor = { zoom_disable_aa = true } })

-- =============================================================================
-- 2. APPLICATION LAUNCHERS (UWSM Wrapped)
-- =============================================================================

-- Launchers for Q/W/E/R are in edit_here/source/keybinds.lua (app-dependent)

-- Menus
hl.bind("ALT + SPACE",        hl.dsp.exec_cmd("pkill rofi; rofi -show drun -run-command 'uwsm app -- {cmd}'"),                          { description = "Launch Menu for Apps" })
hl.bind("CTRL + SHIFT + SPACE",hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. home .. "/user_scripts/rofi/keybindings.sh"),              { description = "Show Keybinds" })
hl.bind(mainMod .. " + CTRL + SPACE",  hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/emoji.sh"),                     { description = "Search Emojis" })
hl.bind(mainMod .. " + CTRL + SHIFT + SPACE", hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/calculator.sh"),         { description = "Calculator" })
hl.bind(mainMod .. " + SHIFT + SPACE", hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/rofi_theme.sh"),                 { description = "Matugen Theme Config" })
hl.bind("CTRL + SPACE",        hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/rofi_wallpaper_selctor.sh"),             { description = "Rofi Wallpaper Selector" })
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("gdbus call --session --dest com.github.dusky.controlcenter --object-path /com/github/dusky/controlcenter --method org.freedesktop.Application.Activate '{}'"), { description = "System Menu" })
hl.bind("CTRL + ALT + SPACE",  hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/dusky_glance.sh"),                      { description = "Dusky Glance" })

-- Rofi Powermenu
hl.bind("ALT + SHIFT + SPACE", hl.dsp.exec_cmd("uwsm-app -- pkill rofi; rofi -show power-menu -modi power-menu:" .. scripts .. "/rofi/powermenu.sh"), { description = "Power Menu" })

-- System Monitor (btop)
hl.bind("CTRL + SHIFT + escape", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " --class btop -e btop"), { description = "System Monitor" })

-- --- System Utilities ---
hl.bind("ALT + 1", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " --class wifitui -e wifitui"),                        { description = "Wi-Fi Manager" })
hl.bind("ALT + 2", hl.dsp.exec_cmd("uwsm-app -- blueman-manager"),                                                      { description = "Bluetooth Manager" })
hl.bind("ALT + 3", hl.dsp.exec_cmd("uwsm-app -- pavucontrol"),                                                          { description = "Audio Mixer" })
hl.bind("ALT + 4", hl.dsp.exec_cmd("uwsm-app -- waypaper"),                                                             { description = "Wallpaper App" })
hl.bind(mainMod .. " + apostrophe",       hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/theme_matugen/theme_ctl.sh next"),             { description = "Cycle Next Wallpaper" })
hl.bind(mainMod .. " + SHIFT + apostrophe", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/rofi/rofi_wallpaper_selctor.sh --next-fav"), { description = "Cycle Fav Wallpaper" })

-- Drive Locking/Unlocking (Browser)
hl.bind("ALT + 5",       hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " -e " .. scripts .. "/drives/drive_manager.sh unlock browser"), { description = "Unlock Browser" })
hl.bind("ALT + SHIFT + 5", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " -e " .. scripts .. "/drives/drive_manager.sh lock browser"),  { locked = true, description = "Lock Browser" })

-- =============================================================================
-- PASSTHROUGH / GAME MODE (disables all other keybinds)
-- =============================================================================
-- Enter passthrough: show notification then switch submap
hl.bind("ALT + 6",
    hl.dsp.exec_cmd("notify-send -u critical -t 3000 'Passthrough Enabled' 'Press ALT+6 to exit'; hyprctl dispatch submap passthrough"),
    { locked = true, description = "Disable Game Mode (Disable Keybinds)" })

hl.define_submap("passthrough", function()
    -- Only bind active inside passthrough: exit key
    hl.bind("ALT + 6",
        hl.dsp.exec_cmd("notify-send -u low -t 2000 'Passthrough Disabled' 'Keybinds restored'; hyprctl dispatch submap reset"),
        { locked = true, description = "Game Mode (Enable Keybinds)" })
end)

-- --- Display Management (ASUS TUF F15) ---
hl.bind("ALT + 7", hl.dsp.exec_cmd("hyprctl keyword monitor eDP-1,1920x1080@48,0x0,1.6 && sleep 2 && hyprctl keyword misc:vrr 0"),  { locked = true, description = "Set Refresh rate to 48Hz Asus Tuf" })
hl.bind("ALT + 8", hl.dsp.exec_cmd("hyprctl keyword monitor eDP-1,1920x1080@144,0x0,1.6 && sleep 2 && hyprctl keyword misc:vrr 1"), { locked = true, description = "Set Refresh rate to 144Hz Asus Tuf" })

-- --- Screen Rotate ---
hl.bind("CTRL + ALT + R",       hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/hypr/screen_rotate.sh -90"), { locked = true, description = "Rotate Screen Clockwise" })
hl.bind("CTRL + ALT + SHIFT + R", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/hypr/screen_rotate.sh +90"), { locked = true, description = "Rotate Screen Anti-Clockwise" })

-- --- Screen DPMS toggle ---
hl.bind("ALT + F7", hl.dsp.exec_cmd("sleep 1 && hyprctl dispatch dpms off"), { locked = true, description = "Screen Off DPMS" })
hl.bind("ALT + F8", hl.dsp.exec_cmd("hyprctl dispatch dpms on"),              { locked = true, description = "Screen On DPMS" })

-- Waybar
hl.bind("ALT + 9",              hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/waybar/waybar_autostart.sh"),          { description = "Start Waybar for 1 Min" })
hl.bind("ALT + 0",              hl.dsp.exec_cmd("pkill waybar"),                                                        { locked = true, description = "Kill Waybar" })
hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/waybar/dusky_waybars.sh --toggle"),   { description = "Waybar Swap Configs" })
hl.bind(mainMod .. " + ALT + SHIFT + W", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/waybar/dusky_waybars.sh --back_toggle"), { description = "Waybar Swap Configs (Back)" })

-- wlogout
hl.bind("ALT + F4", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/wlogout/wlogout_scale.sh"), { description = "Logout Menu" })

-- Hyprland Reload
hl.bind("ALT + R", hl.dsp.exec_cmd("hyprctl reload"), { locked = true, description = "Reload Hyprland" })

-- Dusky QuickPanel (Sliders)
hl.bind("ALT + V", hl.dsp.exec_cmd("gdbus call --session --dest org.dusky.quickpanal --object-path /org/dusky/quickpanal --method org.freedesktop.Application.Activate '{}'"), { description = "Dusky QuickPanel" })

-- =============================================================================
-- 3. CUSTOM SCRIPTS & UTILITIES
-- =============================================================================

-- ASUS Hardware: Fan & Keyboard Light Control
hl.bind("XF86Launch3", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " --class asusctl.sh -e sudo " .. scripts .. "/asus/asusctl.sh"), { description = "ASUS Control" })

-- Display Scale Adjustment
hl.bind(mainMod .. " + F",       hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/hypr/adjust_scale.py +"), { locked = true, repeating = true, description = "Scale Up" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/hypr/adjust_scale.py -"), { locked = true, repeating = true, description = "Scale Down" })

-- Performance: Process Terminator
hl.bind(mainMod .. " + semicolon", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " --class performance.sh -e " .. scripts .. "/performance/services_and_process_terminator.sh"), { description = "Kill Process" })

-- wayclick script
hl.bind(mainMod .. " + U",       hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/wayclick/dusky_wayclick.sh"),          { description = "Key Press Sound" })
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/mako_osd/dusky_keys/dusky_keys.sh"), { description = "OSD Key Presses" })

-- Opacity & Blur Toggles
hl.bind(mainMod .. " + ALT + period", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/hypr/hypr_blur_opacity_shadow_toggle.sh"), { locked = true, description = "Toggle Blur/Opacity" })
hl.bind(mainMod .. " + period", hl.dsp.window.set_prop({ prop = "opaque",   value = "toggle" }), { locked = true, description = "Toggle Per-Window Opacity" })
hl.bind(mainMod .. " + comma",  hl.dsp.window.set_prop({ prop = "no_blur",  value = "toggle" }), { locked = true, description = "Toggle Per-Window Blur" })

-- --- Accessibility: Zoom ---
hl.bind("SUPER + equal", hl.dsp.exec_cmd("sh -c \"hyprctl keyword cursor:zoom_factor \\\"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {print $2 * 1.25}')\\\"\""),                                                            { repeating = true, description = "Zoom In" })
hl.bind("SUPER + minus",  hl.dsp.exec_cmd("sh -c \"hyprctl keyword cursor:zoom_factor \\\"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {val = $2 / 1.25; if (val < 1.0) val = 1.0; print val}')\\\"\""),                       { repeating = true, description = "Zoom Out" })
hl.bind("SUPER + BACKSPACE", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"), { locked = true, description = "Reset Zoom" })

-- Hyprshade (Visual Filters)
hl.bind(mainMod .. " + ALT + S", hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/shader_menu.sh"),       { description = "Shader Menu" })
hl.bind(mainMod .. " + ALT + X", hl.dsp.exec_cmd("hyprshade off"),                                                         { locked = true, description = "Disable Shader" })
hl.bind(mainMod .. " + ALT + V", hl.dsp.exec_cmd("hyprshade on vibrance"),                                                 { locked = true, description = "Vibrant Shader" })

-- Hyprland Animations Rofi Menu
hl.bind(mainMod .. " + ALT + A", hl.dsp.exec_cmd("uwsm-app -- pkill rofi; rofi -show animations -modi 'animations:" .. scripts .. "/rofi/hypr_anim.sh'"), { description = "Animation Rofi Menu" })

-- --- Clipboard & Screenshot ---

-- Rofi Clipboard
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("uwsm-app -- pkill rofi; rofi -modi 'clipboard:" .. scripts .. "/rofi/rofi_cliphist.sh' -show clipboard"), { description = "Clipboard History" })

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"), { description = "Color Picker" })

-- Screenshots
hl.bind(mainMod .. " + S",             hl.dsp.exec_cmd(scripts .. "/images/dusky_screenshot.sh --region --freeze --no-notify"),                                  { description = "Quick Screenshot" })
hl.bind("SHIFT + Print",               hl.dsp.exec_cmd("grim - | wl-copy && notify-send 'Fullscreen Screenshot in Clipboard'"),                                   { locked = true, description = "Full Screen Quick Screenshot" })
hl.bind(mainMod .. " + SHIFT + S",     hl.dsp.exec_cmd(scripts .. "/images/dusky_screenshot.sh --region --freeze --annotate --no-notify --tool arrow"),           { description = "Screenshot and Annotation" })
hl.bind("Print",                        hl.dsp.exec_cmd("pgrep -x swappy || (grim - | uwsm-app -- satty -f -)"),                                                  { description = "Fullscreen Screenshot and Annotation" })
hl.bind("SHIFT + CTRL + ALT + SPACE",  hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/dusky_rofi_screenshot.sh"),                               { description = "Dusky Screenshoter" })

-- Google Image Search
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd(scripts .. "/google_image_search/google_image_search.sh"), { description = "Image Search (Select and search)" })

-- OCR (Tesseract)
hl.bind(mainMod .. " + T",       hl.dsp.exec_cmd("pgrep tesseract || (slurp | grim -g - - | tesseract stdin stdout -l eng | wl-copy)"), { description = "OCR Selection" })
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("grim - | tesseract stdin stdout -l eng | wl-copy"),                                  { description = "OCR Fullscreen" })

-- Ollama Sidebar
hl.bind(mainMod .. " + ALT + O", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " --class ollama_terminal.sh -e " .. scripts .. "/llm/ollama_terminal.sh"), { description = "AI LLM Ollama Chat" })

-- Music Recognition
hl.bind(mainMod .. " + ALT + M", hl.dsp.exec_cmd("uwsm-app -- " .. terminal .. " --hold --class music_recognition.sh -e " .. scripts .. "/music/music_recognition.sh"), { description = "Music Recognition aka Shazam" })

-- --- AI & Voice Tools ---
hl.bind(mainMod .. " + O",       hl.dsp.exec_cmd("wl-copy \"$(wl-paste -p)\" && uwsm-app -- " .. scripts .. "/tts_stt/dusky_kokoro/trigger.sh"),         { description = "TTS Kokoro GPU" })
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/audio/router/TTS_VC.sh"),                                              { description = "TTS VC" })
hl.bind(mainMod .. " + I",       hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/tts_stt/dusky_parakeet/trigger.sh"),                                     { description = "STT Parakeet GPU" })

-- =============================================================================
-- NOTIFICATION ACTIONS (MAKO + ROFI)
-- =============================================================================
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("uwsm-app -- pkill rofi; " .. scripts .. "/rofi/rofi_mako.sh"),                                       { description = "Notification History" })
hl.bind(mainMod .. " + ALT + D",   hl.dsp.exec_cmd("makoctl dismiss -a"),                                                                                  { locked = true, description = "Clear Screen Notifications" })
hl.bind(mainMod .. " + ALT + F",   hl.dsp.exec_cmd("makoctl menu -- rofi -dmenu -p 'Action: '"),                                                          { description = "Interact with Current Notification" })

-- --- Screen Lock ---
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/hyprlock/lock.sh"), { description = "Lock Screen" })

-- =============================================================================
-- 4. WINDOW MANAGEMENT
-- =============================================================================
hl.bind(mainMod .. " + C",         hl.dsp.window.close(),                                                          { description = "Close Window" })
hl.bind(mainMod .. " + A",         hl.dsp.window.fullscreen({ mode = "fullscreen" }),                              { description = "Window Fullscreen" })
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.window.fullscreen({ mode = "maximized" }),                              { description = "Window Maximize" })
hl.bind(mainMod .. " + X",         hl.dsp.window.pin(),                                                            { description = "Pin Window" })
hl.bind(mainMod .. " + Y",         hl.dsp.layout("togglesplit"),                                                   { description = "Toggle Window Split" })
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.window.pseudo(),                                                         { description = "Toggle Pseudo" })

-- Smart Float: Toggle float → Resize to 90% → Center
hl.bind(mainMod .. " + D",
    hl.dsp.exec_cmd("if hyprctl -j activewindow | jq -e '.floating | not'; then hyprctl --batch 'dispatch togglefloating; dispatch resizeactive exact 90% 90%; dispatch centerwindow'; else hyprctl dispatch togglefloating; fi"),
    { description = "Toggle Float" })

-- --- Focus Movement (hold-repeatable) ---
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "l" }), { repeating = true, description = "Focus Left" })
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "r" }), { repeating = true, description = "Focus Right" })
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "u" }), { repeating = true, description = "Focus Up" })
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "d" }), { repeating = true, description = "Focus Down" })

-- --- Window Movement (hold-repeatable) ---
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }), { repeating = true, description = "Move Left" })
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }), { repeating = true, description = "Move Right" })
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }), { repeating = true, description = "Move Up" })
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }), { repeating = true, description = "Move Down" })

-- --- Window Resizing (hold-repeatable) ---
hl.bind(mainMod .. " + right", hl.dsp.window.resize({ x =  30, y =   0, relative = true }), { repeating = true, description = "Resize Width +" })
hl.bind(mainMod .. " + left",  hl.dsp.window.resize({ x = -30, y =   0, relative = true }), { repeating = true, description = "Resize Width -" })
hl.bind(mainMod .. " + up",    hl.dsp.window.resize({ x =   0, y = -30, relative = true }), { repeating = true, description = "Resize Height -" })
hl.bind(mainMod .. " + down",  hl.dsp.window.resize({ x =   0, y =  30, relative = true }), { repeating = true, description = "Resize Height +" })

-- =============================================================================
-- 5. WORKSPACE MANAGEMENT (Context-Aware / Banked)
-- =============================================================================

local ws_script = home .. "/user_scripts/hypr/multi_monitor_workspace.sh"

-- Switch to Workspace (Context Relative)
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(ws_script .. " workspace " .. i),            { description = "Switch To Context " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.exec_cmd(ws_script .. " movetoworkspace " .. i), { description = "Move To Context " .. i })
    hl.bind(mainMod .. " + ALT + " .. key, hl.dsp.exec_cmd(ws_script .. " movetoworkspacesilent " .. i), { description = "Silent Move To Context " .. i })
end

-- --- Back and forth with last workspace ---
hl.bind(mainMod .. " + TAB",       hl.dsp.focus({ workspace = "previous" }), { repeating = true, description = "Last Workspace" })

-- Cycle Workspaces
hl.bind("ALT + SHIFT + TAB",       hl.dsp.focus({ workspace = "e-1" }), { repeating = true, description = "Cycle Backward" })
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.focus({ workspace = "e+1" }), { repeating = true, description = "Cycle Next WS" })

-- Special Workspace (Scratchpad)
hl.bind(mainMod .. " + Z",         hl.dsp.workspace.toggle_special("magic"),                         { description = "Toggle Scratchpad" })
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.window.move({ workspace = "special:magic" }),              { description = "Move to Scratchpad" })

-- Special Workspace for Spotify
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/spotify/spotify_toggle.sh"))

-- =============================================================================
-- 6. MOUSE BINDINGS
-- =============================================================================
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true, description = "Move Window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize Window" })

-- =============================================================================
-- 7. HARDWARE & MEDIA KEYS
-- =============================================================================

-- Volume
hl.bind("XF86AudioRaiseVolume",     hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --vol-up 5"),   { locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume",     hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --vol-down 5"), { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute",            hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --vol-mute"),   { locked = true, repeating = true, description = "Mute" })
hl.bind("XF86AudioMicMute",         hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --mic-mute"),   { locked = true, repeating = true, description = "Mute microphone" })

-- Brightness
hl.bind("XF86MonBrightnessUp",      hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --bright-up 5"),   { locked = true, repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown",    hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --bright-down 5"), { locked = true, repeating = true, description = "Brightness down" })

-- Precise Adjustments (Alt Modifier)
hl.bind("ALT + XF86AudioRaiseVolume",  hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --vol-up 1"),    { locked = true, repeating = true, description = "Volume up precise" })
hl.bind("ALT + XF86AudioLowerVolume",  hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --vol-down 1"),  { locked = true, repeating = true, description = "Volume down precise" })
hl.bind("ALT + XF86MonBrightnessUp",   hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --bright-up 1"),   { locked = true, repeating = true, description = "Brightness up precise" })
hl.bind("ALT + XF86MonBrightnessDown", hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --bright-down 1"), { locked = true, repeating = true, description = "Brightness down precise" })

-- Keyboard Backlight
hl.bind("XF86KbdBrightnessUp",   hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --kbd-bright-up 10"),   { locked = true, repeating = true, description = "Keyboard Brightness up" })
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --kbd-bright-down 10"), { locked = true, repeating = true, description = "Keyboard Brightness down" })

-- Player Controls (routed through script for OSD feedback)
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --next"),       { locked = true, description = "Next track" })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --prev"),       { locked = true, description = "Previous track" })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --play-pause"), { locked = true, description = "Play" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --play-pause"), { locked = true, description = "Pause" })
hl.bind("XF86AudioStop",  hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --stop"),       { locked = true, description = "Stop" })
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --play-pause"), { locked = true, description = "Toggle Pause" })

-- Custom Audio/Mic Switching Scripts
hl.bind("ALT + P", hl.dsp.exec_cmd(scripts .. "/mako_osd/osd_router/osd_router.sh --vol-mute"), { locked = true, description = "Mute Audio" })
hl.bind("ALT + M", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/audio/mono_audio_pipewire.py"), { locked = true, description = "Mono Audio Toggle" })
hl.bind("ALT + O", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/audio/audio_switch.sh"),        { locked = true, description = "Switch Audio Output" })
hl.bind("ALT + I", hl.dsp.exec_cmd("uwsm-app -- " .. scripts .. "/audio/mic_switch.sh"),          { locked = true, description = "Switch Mic Input" })

-- Calculator
hl.bind("XF86Calculator", hl.dsp.exec_cmd("uwsm-app -- gnome-calculator"), { description = "Calculator" })
