-- =============================================================================
-- MONITORS — Base Configuration
-- =============================================================================
-- DO NOT EDIT THIS FILE.
-- Configure your monitors in ~/.config/hypr/edit_here/source/monitors.lua
-- which is loaded last and overrides these defaults.
-- =============================================================================

-- Fallback: auto-detect all connected monitors with preferred mode
-- This is intentionally minimal; actual setup lives in edit_here.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
