-- =============================================================================
-- WINDOW RULES & LAYER RULES
-- =============================================================================
-- DO NOT EDIT THIS FILE.
-- Add custom rules in ~/.config/hypr/edit_here/source/window_rules.lua
-- =============================================================================

-- -----------------------------------------------------------------------------
-- GLOBAL / XWAYLAND SETTINGS
-- -----------------------------------------------------------------------------
hl.config({ xwayland = { force_zero_scaling = true } })

-- -----------------------------------------------------------------------------
-- APPLICATION-SPECIFIC FLOATS & VISUALS
-- -----------------------------------------------------------------------------

--— Firefox: Float "About" Dialog —
hl.window_rule({ name = "float-firefox-about",   match = { title = "^(About Mozilla Firefox)$"  }, float = true })

--— Firefox: Float "Library" Window —
hl.window_rule({ name = "float-firefox-library", match = { class = "^(firefox)$", title = "^(Library)$" }, float = true })

--— Firefox: YouTube Full Opacity —
hl.window_rule({ name = "opaque-firefox-youtube", match = { class = "^(firefox)$", title = ".*YouTube.*" }, opaque = true })

--— Firefox: Figma Full Opacity —
hl.window_rule({ name = "opaque-firefox-figma",  match = { class = "^(firefox)$", title = ".*Figma.*"   }, opaque = true })

--— Firefox: Pixabay Full Opacity —
hl.window_rule({ name = "opaque-firefox-pixabay", match = { class = "^(firefox)$", title = ".*Pixabay.*" }, opaque = true })

--— MPV: Always Float & Small —
hl.window_rule({ name = "float-mpv", match = { class = "^(mpv)$" }, float = true, opaque = true, size = "640 360", center = true })

--— Wine/Proton: Hide empty tray windows —
hl.window_rule({ name = "xembedsniproxy", match = { class = "^$", title = "^$" }, opacity = "0.0 override 0.0 override", no_blur = true })

-- -----------------------------------------------------------------------------
-- QBITTORRENT: Floating Logic (Layered Approach)
-- -----------------------------------------------------------------------------

-- 1. Default Policy: Float ALL qBittorrent windows
hl.window_rule({ name = "float_qbittorrent_all", match = { class = "^(org.qbittorrent.qBittorrent)$" }, float = true, center = true, size = "650 450" })

-- 2. Exception: Force the Main Window to Tile
hl.window_rule({ name = "tile_qbittorrent_main", match = { class = "^(org.qbittorrent.qBittorrent)$", title = "^(qBittorrent v).*$" }, float = false })

-- -----------------------------------------------------------------------------
-- GAMES AND GAME LAUNCHERS
-- -----------------------------------------------------------------------------
hl.window_rule({ name = "PrismLauncher", match = { class = "org.prismlauncher.PrismLauncher" }, float = true })
hl.window_rule({ name = "Minecraft",     match = { class = "com.mojang.minecraft.java-edition" }, opaque = true })
hl.window_rule({ name = "Tetr.io",       match = { class = "tetrio-desktop" }, opaque = true })
hl.window_rule({ name = "SuperTuxKart",  match = { class = "supertuxkart" }, opaque = true })
hl.window_rule({ name = "ROBLOX",        match = { class = "org.vinegarhq.Sober" }, opaque = true })

-- -----------------------------------------------------------------------------
-- STEAM
-- -----------------------------------------------------------------------------
hl.window_rule({ name = "steam-general",     match = { class = "^(steam)$" }, float = true, opaque = true })
hl.window_rule({ name = "steam-main-window", match = { class = "^(steam)$", title = "^(Steam)$" }, size = "1100 600", center = true })
hl.window_rule({ name = "steam-friends",     match = { class = "^(steam)$", title = "^(Friends List)$" }, size = "460 580" })
hl.window_rule({ name = "steam-idle",        match = { class = "^(steam)$" }, idle_inhibit = "fullscreen" })

-- -----------------------------------------------------------------------------
-- SHOW ME THE KEY (Key Visualizer)
-- -----------------------------------------------------------------------------
hl.window_rule({
    name  = "showmethekey-floating",
    match = { class = "^(showmethekey-gtk)$", title = "^(Floating Window - Show Me The Key)$" },
    float   = true,
    pin     = true,
    size    = "470 50",
    move    = "((monitor_w-window_w)/2) (monitor_h-window_h-20)",
    no_dim  = true,
    border_size = 0,
    opaque  = true,
})

-- -----------------------------------------------------------------------------
-- COMMON DESKTOP / GNOME / QT UTILITIES
-- -----------------------------------------------------------------------------
hl.window_rule({ name = "uGet",              match = { title = "^(uGet)$"                                        }, float = true, size = "889 505", center = true })
hl.window_rule({ name = "float-calculator",  match = { class = "^(org.gnome.Calculator)$"                        }, float = true, size = "360 616", center = true })
hl.window_rule({ name = "gnome-camera",      match = { class = "^(org.gnome.Snapshot)$"                          }, float = true, size = "528 298", center = true })
hl.window_rule({ name = "float-cameractrls", match = { class = "^(hu.irl.cameractrls)$", title = "^(/dev/.*)$"  }, float = true, size = "624 353", center = true })
hl.window_rule({ name = "float-loupe",       match = { class = "^(org.gnome.Loupe)$"                             }, float = true, size = "900 600", center = true, opaque = true })
hl.window_rule({ name = "float-clocks",      match = { class = "^(org.gnome.clocks)$"                            }, float = true, size = "602 297", center = true })
hl.window_rule({ name = "gparted",           match = { class = "^(GParted)$"                                     }, float = true, size = "652 431", center = true })
hl.window_rule({ name = "grsync",            match = { class = "^(grsync)$"                                      }, float = true, size = "650 458", center = true })
hl.window_rule({ name = "float-blueman",     match = { class = "^(blueman-manager)$"                             }, float = true, size = "530 313", center = true })
hl.window_rule({ name = "handbrake",         match = { class = "^(fr.handbrake.ghb)$"                            }, float = true, size = "970 698", center = true })
hl.window_rule({ name = "seahorse",          match = { class = "^(org.gnome.seahorse.Application)$"              }, float = true, size = "827 632", center = true })
hl.window_rule({ name = "bluetui",           match = { class = "^(bluetui)$"                                     }, float = true, size = "551 362", center = true })
hl.window_rule({ name = "airmon_ng",         match = { class = "^(airmon_ng.sh)$"                                }, float = true, size = "775 450", center = true })
hl.window_rule({ name = "iphone_vnc",        match = { class = "^(iphone_vnc.sh)$"                               }, float = true, size = "650 423", center = true })
hl.window_rule({ name = "btrfs_stats",       match = { class = "^(btrfs_zstd_compression_stats.sh)$"             }, float = true, size = "650 423", center = true })
hl.window_rule({ name = "tailscale_setup",   match = { class = "^(tailscale_setup)$"                             }, float = true, size = "782 676", center = true })
hl.window_rule({ name = "tailscale_remove",  match = { class = "^(tailscale_uninstall)$"                         }, float = true, size = "775 450", center = true })
hl.window_rule({ name = "kew",               match = { class = "^(kew)$"                                         }, float = true, size = "652 576", center = true })
hl.window_rule({ name = "file_manager_switcher",  match = { class = "^(235_file_manager_switch.sh)$"       }, float = true, size = "634 445", center = true })
hl.window_rule({ name = "browser_switcher",  match = { class = "^(236_browser_switcher.sh)$"                     }, float = true, size = "634 445", center = true })
hl.window_rule({ name = "text_editor_switch",match = { class = "^(237_text_editer_switcher.sh)$"                 }, float = true, size = "634 445", center = true })
hl.window_rule({ name = "terminal_switcher", match = { class = "^(238_terminal_switcher.sh)$"                    }, float = true, size = "634 445", center = true })
hl.window_rule({ name = "plugin_manager",    match = { class = "^(356_dusky_plugin_manager.sh)$"                 }, float = true, size = "772 554", center = true })
hl.window_rule({ name = "ftp_setup",         match = { class = "^(250_ftp_arch.sh)$"                             }, float = true, size = "652 576", center = true })
hl.window_rule({ name = "hosts_block",       match = { class = "^(325_hosts_files_block.sh)$"                    }, float = true, size = "780 548", center = true })
hl.window_rule({ name = "locale_tui",        match = { class = "^(locale_tui.sh)$"                               }, float = true, size = "780 548", center = true })
hl.window_rule({ name = "mako_tui_glance",   match = { class = "^(glance_mako_tui.sh)$"                          }, float = true, size = "780 548", center = true })
hl.window_rule({ name = "change_ftp_dir",    match = { class = "^(change_ftp_directory_server.sh)$"              }, float = true, size = "652 576", center = true })
hl.window_rule({ name = "arp_scan",          match = { class = "^(arp_scan.sh)$"                                 }, float = true, size = "652 576", center = true })
hl.window_rule({ name = "openssh_setup",     match = { class = "^(02_openssh_setup.sh)$"                         }, float = true, size = "652 576", center = true })
hl.window_rule({ name = "clipboard_persist", match = { class = "^(390_clipboard_persistance.sh)$"                }, float = true, size = "805 323", center = true })
hl.window_rule({ name = "cache_purge",       match = { class = "^(cache_purge.sh)$"                              }, float = true, size = "589 529", center = true })
hl.window_rule({ name = "mouse_btn_reverse", match = { class = "^(mouse_button_reverse.sh)$"                     }, float = true, size = "589 529", center = true })
hl.window_rule({ name = "git_config",        match = { class = "^(300_git_config.sh)$"                           }, float = true, size = "726 389", center = true })
hl.window_rule({ name = "new_github_repo",   match = { class = "^(305_new_github_repo_to_backup.sh)$"            }, float = true, size = "726 689", center = true })
hl.window_rule({ name = "relink_github",     match = { class = "^(310_reconnect_and_push_new_changes_to_github.sh)$" }, float = true, size = "726 689", center = true })
hl.window_rule({ name = "io_monitor",        match = { class = "^(io_monitor.sh)$"                               }, float = true, size = "960 300", center = true })
hl.window_rule({ name = "terminal_clipboard",match = { class = "^(terminal_clipboard.sh)$"                       }, float = true, no_anim = true, size = "840 520", center = true })
hl.window_rule({ name = "asusctl",           match = { class = "^(asusctl.sh)$"                                  }, float = true, size = "789 534", center = true })
hl.window_rule({ name = "nvim_reset",        match = { class = "^(01_reset_neovim.sh)$"                          }, float = true, size = "730 454", center = true })
hl.window_rule({ name = "cli_plugins",       match = { class = "^(02_cli_plugins_download.sh)$"                  }, float = true, size = "730 454", center = true })
hl.window_rule({ name = "nvim_manager",      match = { class = "^(dusky_neovim_manager.sh)$"                     }, float = true, size = "532 475", center = true })
hl.window_rule({ name = "paru_optional",     match = { class = "^(090_paru_packages_optional%.sh)$"              }, float = true, size = "831 572"                })
hl.window_rule({ name = "zram_config",       match = { class = "^(205_zram_configuration.sh)$"                   }, float = true, size = "907 377", center = true })
hl.window_rule({ name = "limine_setup",      match = { class = "^(01_limine_setup.sh)$"                          }, float = true, size = "730 454", center = true })
hl.window_rule({ name = "snapper_subvol",    match = { class = "^(02_snapper_isolation_subvolume.sh)$"           }, float = true, size = "730 454", center = true })
hl.window_rule({ name = "snapper_hooks",     match = { class = "^(03_snapper_pacman_hooks.sh)$"                  }, float = true, size = "730 454", center = true })
hl.window_rule({ name = "swappiness",        match = { class = "^(210_zram_optimize_swappiness%.sh)$"            }, float = true, size = "938 500", center = true })
hl.window_rule({ name = "gpu_env",           match = { class = "^(000_configure_uwsm_gpu%.sh)$"                  }, float = true, size = "702 492", center = true })
hl.window_rule({ name = "wayclick_setup",    match = { class = "^(dusky_wayclick.sh)$"                           }, float = true, size = "831 572"                })
hl.window_rule({ name = "wayclick_tui",      match = { class = "^(dusky_tui_wayclick.sh)$"                       }, float = true, size = "780 510"                })
hl.window_rule({ name = "wayclick_sounds",   match = { class = "^(wayclick_soundpacks_download.sh)$"             }, float = true, size = "580 810"                })
hl.window_rule({ name = "tty_autologin",     match = { class = "^(285_tty_autologin.sh)$"                        }, float = true, size = "730 454", center = true })
hl.window_rule({ name = "dusky_monitor",     match = { class = "^(dusky_monitor.sh)$"                            }, float = true, size = "802 469", center = true })
hl.window_rule({ name = "dusky_keybinds",    match = { class = "^(dusky_keybinds.sh)$"                           }, float = true, size = "(monitor_w*0.9) (monitor_h*0.9)", move = "(monitor_w*0.05) (monitor_h*0.05)" })
hl.window_rule({ name = "dusky_appearances", match = { class = "^(dusky_appearances.sh)$"                        }, float = true, size = "781 507", center = true })
hl.window_rule({ name = "dusky_workspace",   match = { class = "^(dusky_workspace_manager.sh)$"                  }, float = true, size = "781 507", center = true })
hl.window_rule({ name = "dusky_matugen",     match = { class = "^(dusky_matugen_presets.sh)$"                    }, float = true, size = "820 620", center = true })
hl.window_rule({ name = "dusky_input",       match = { class = "^(dusky_input.sh)$"                              }, float = true, size = "781 507", center = true })
hl.window_rule({ name = "tui_mako",          match = { class = "^(tui_mako.sh)$"                                 }, float = true, size = "781 507", center = true })
hl.window_rule({ name = "dusky_gsettings",   match = { class = "^(dusky_gsettings.sh)$"                          }, float = true, size = "781 507", center = true })
hl.window_rule({ name = "dconf_editor",      match = { class = "^(ca%.desrt%.dconf-editor)$"                     }, float = true, size = "979 642"                })
hl.window_rule({ name = "dusky_power",       match = { class = "^(dusky_power.sh)$"                              }, float = true, size = "790 530", center = true })
hl.window_rule({ name = "dusky_battery",     match = { class = "^(dusky_battery_notify.sh)$"                     }, float = true, size = "790 530", center = true })
hl.window_rule({ name = "battery_service",   match = { class = "^(135_battery_notify_service.sh)$"               }, float = true, size = "504 501", center = true })
hl.window_rule({ name = "dusky_hypridle",    match = { class = "^(dusky_hypridle.sh)$"                           }, float = true, size = "784 529", center = true })
hl.window_rule({ name = "fastfetch",         match = { class = "^(fastfetch)$"                                   }, float = true, size = "943 393", center = true })
hl.window_rule({ name = "dusky_winrules",    match = { class = "^(dusky_window_rules.sh)$"                       }, float = true, size = "1000 750", center = true })
hl.window_rule({ name = "dysk",             match = { class = "^(dysk)$"                                        }, float = true, size = "1005 298", center = true })
hl.window_rule({ name = "performance",       match = { class = "^(performance.sh)$"                              }, float = true, size = "566 569", center = true })

-- Kokoro TTS: Floating corner widget
hl.window_rule({
    name  = "kokoro",
    match = { class = "^(kokoro)$" },
    float   = true,
    pin     = true,
    size    = "254 90",
    move    = "(monitor_w-window_w-8) (monitor_h-window_h-8)",
    no_dim  = true,
    opaque  = true,
})

hl.window_rule({ name = "kokoro_installer",   match = { class = "^(kokoro_installer.sh)$"   }, float = true, pin = true, size = "876 601" })
hl.window_rule({ name = "parakeet_installer", match = { class = "^(parakeet_installer.sh)$" }, float = true, pin = true, size = "876 601" })
hl.window_rule({ name = "peaclock",           match = { class = "^(peaclock)$"              }, float = true, size = "406 179", center = true })
hl.window_rule({ name = "wifitui",            match = { class = "^(wifitui)$"              }, float = true, size = "596 318", center = true })
hl.window_rule({ name = "dusky_network",      match = { class = "^(dusky_network.sh)$"     }, float = true, size = "741 579", center = true })
hl.window_rule({ name = "tray_tui",           match = { class = "^(tray-tui)$"             }, float = true, size = "791 488", center = true })
hl.window_rule({ name = "cava",               match = { class = "^(cava)$"                 }, float = true, size = "791 488", center = true })
hl.window_rule({ name = "htop",               match = { class = "^(htop)$"                 }, float = true, size = "1080 607", center = true })
hl.window_rule({ name = "dgop",               match = { class = "^(dgop)$"                 }, float = true, size = "1080 607", center = true })
hl.window_rule({ name = "btop",               match = { class = "^(btop)$"                 }, float = true, size = "1080 607", center = true })
hl.window_rule({ name = "nvim",               match = { class = "^(nvim)$"                 }, float = true, size = "455 549", center = true })

-- GNOME Text Editor: large editor for hypr config
hl.window_rule({ name = "gnome-text-editor", match = { class = "^(org.gnome.TextEditor)$" },
    float = true, size = "(monitor_w*0.65) (monitor_h*0.92)", move = "(monitor_w*0.05) (monitor_h*0.05)", center = true })

hl.window_rule({ name = "errands",     match = { title = "^(Errands)$"                                               }, float = true, size = "519 614", center = true })
hl.window_rule({ name = "backups",     match = { class = "^(thunar)$", title = "^(dusky_backups - Thunar)$"          }, float = true, size = "(monitor_w*0.5612) (monitor_h*0.8)", center = true })
hl.window_rule({ name = "yazi_backup", match = { class = "^(yazi)$",   title = "^(Backup Viewer)$"                   }, float = true, size = "(monitor_w*0.6283) (monitor_h*0.8600)", center = true })

-- Dusky Control Center
hl.window_rule({
    name  = "dusky_control_center",
    match = { title = "^(Dusky Control Center)$", class = "^(com.github.dusky.controlcenter)$" },
    float     = true,
    animation = "slide down",
    size      = "(monitor_w*0.50) (monitor_h*0.92)",
    center    = true,
})

-- Dusky QuickPanel (sliders)
hl.window_rule({
    name  = "dusky_quickpanal",
    match = { title = "^(dusky_quickpanal.py)$", class = "^(org.dusky.quickpanal)$" },
    float      = true,
    animation  = "slide right",
    no_dim     = true,
    rounding   = 20,
    move       = "(monitor_w-window_w-20) (monitor_h-window_h-20)",
    border_size = 0,
})

hl.window_rule({ name = "audiorouter-popup", match = { class = "^(dev%.audiorouter%.popup)$" }, float = true, center = true, size = "(monitor_w*0.4557) (monitor_h*0.9324)" })
hl.window_rule({ name = "disks",             match = { title = "^(Disks)$", class = "^(org.gnome.DiskUtility)$" }, float = true, size = "890 512", center = true })
hl.window_rule({ name = "baobab",            match = { class = "^(org.gnome.baobab)$"                           }, float = true, size = "1152 648", center = true })
hl.window_rule({ name = "thunar_rename",     match = { class = "Thunar", title = "^Rename.*$"                   }, float = true })

hl.window_rule({ name = "sysbench",          match = { class = "^(sysbench_benchmark.sh)$"   }, float = true, size = "567 658", center = true })
hl.window_rule({ name = "ntfs_fix",          match = { class = "^(ntfs_fix.sh)$"             }, float = true, size = "766 485", center = true })
hl.window_rule({ name = "power_saver",       match = { class = "^(power_saver.sh)$"          }, float = true, size = "737 628", center = true })
hl.window_rule({ name = "power_saver_off",   match = { class = "^(power_saver_off.sh)$"      }, float = true, size = "568 456", center = true })
hl.window_rule({ name = "aur_fallback",      match = { class = "^(080_aur_paru_fallback_yay.sh)$" }, float = true, size = "567 658", center = true })
hl.window_rule({ name = "warp_setup",        match = { class = "^(085_warp.sh)$"             }, float = true, size = "567 658", center = true })
hl.window_rule({ name = "preload_config",    match = { class = "^(335_preload_config.sh)$"   }, float = true, size = "889 669", center = true })
hl.window_rule({ name = "sddm_setup",        match = { class = "^(465_sddm_setup.sh)$"      }, float = true, size = "889 669", center = true })
hl.window_rule({ name = "update_dusky",      match = { class = "^(update_dusky.sh)$"         }, float = true, size = "1192 710", center = true })
hl.window_rule({ name = "system_update",     match = { class = "^(system_update.sh)$"        }, float = true, pin = true, size = "1192 710", center = true })

hl.window_rule({ name = "ORCHESTRA",         match = { class = "^(ORCHESTRA.sh)$"            }, float = true, size = "(monitor_w*0.9) (monitor_h*0.9)", move = "(monitor_w*0.05) (monitor_h*0.05)" })
hl.window_rule({ name = "deploy_dotfiles",   match = { class = "^(deploy_dotfiles.sh)$"      }, float = true, size = "(monitor_w*0.9) (monitor_h*0.9)", move = "(monitor_w*0.05) (monitor_h*0.05)" })
hl.window_rule({ name = "restore_stash",     match = { class = "^(restore_stash.sh)$"        }, float = true, size = "1192 710", center = true })
hl.window_rule({ name = "send_logs",         match = { class = "^(send_logs.sh)$"            }, float = true, size = "500 250",  center = true })
hl.window_rule({ name = "about_dusky",       match = { class = "^(about_dusky.sh)$"          }, float = true, size = "503 264",  center = true })

-- Ollama sidebar: left-edge slide panel
hl.window_rule({
    name  = "ollama_sidebar",
    match = { class = "^(ollama_terminal.sh)$" },
    float     = true,
    size      = "(monitor_w*0.28) (monitor_h*0.88)",
    animation = "slide left",
    rounding  = 9,
    move      = "(monitor_w*0.038) (monitor_h*0.5 - window_h*0.5)",
})

hl.window_rule({ name = "dusky_service_toggle", match = { class = "^(dusky_service_toggle.sh)$" }, float = true, size = "840 598", center = true })

-- WireGuard terminal windows
hl.window_rule({ name = "dusky_wg_new",    match = { class = "^(dusky_wg_new)$"    }, float = true, size = "700 480", center = true })
hl.window_rule({ name = "dusky_wg_setup",  match = { class = "^(dusky_wg_setup)$"  }, float = true, size = "700 420", center = true })
hl.window_rule({ name = "dusky_wg_status", match = { class = "^(dusky_wg_status)$" }, float = true, size = "720 400", center = true })
hl.window_rule({ name = "dusky_wg_edit",   match = { class = "^(dusky_wg_edit)$"   }, float = true, size = "700 420", center = true })
hl.window_rule({ name = "dusky_wg_delete", match = { class = "^(dusky_wg_delete)$" }, float = true, size = "500 200", center = true })

hl.window_rule({ name = "music_recognition",      match = { class = "^(music_recognition.sh)$"       }, float = true, size = "409 147", center = true })
hl.window_rule({ name = "hyprlock_switcher",       match = { class = "^(dusky_hyprlock_switcher.sh)$" }, float = true, size = "821 508", center = true })
hl.window_rule({ name = "dusky_waybars",           match = { class = "^(dusky_waybars.sh)$"           }, float = true, size = "780 510", center = true })
hl.window_rule({ name = "float-zathura",           match = { class = "^(org.pwmt.zathura)$"           }, float = true, size = "655 526", center = true })
hl.window_rule({ name = "float-waypaper",          match = { class = "^(waypaper)$"                   }, float = true, size = "786 492", center = true })
hl.window_rule({ name = "float-share-picker",      match = { class = "^(hyprland-share-picker)$"      }, float = true, size = "500 300", center = true })
hl.window_rule({ name = "float-nwg-look",          match = { class = "^(nwg-look)$"                   }, float = true, size = "627 464", center = true })
hl.window_rule({ name = "float-kvantum",           match = { class = "^(kvantummanager)$"             }, float = true, size = "585 512", center = true })
hl.window_rule({ name = "float-qt6ct",             match = { class = "^(qt6ct)$"                      }, float = true, size = "700 609", center = true })
hl.window_rule({ name = "float-qt5ct",             match = { class = "^(qt5ct)$"                      }, float = true, size = "636 665", center = true })
hl.window_rule({ name = "float-guifetch",          match = { class = "^(guifetch)$"                   }, float = true, size = "800 500", center = true })
hl.window_rule({ name = "float-pavucontrol",       match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol)$" }, float = true, size = "643 422", center = true })
hl.window_rule({ name = "float-nm-editor",         match = { class = "^(nm-connection-editor)$"       }, float = true, size = "432 423", center = true })

hl.window_rule({ name = "float_vm_viewer",  match = { class = "^(virt-manager)$", title = "^(.* on QEMU/KVM)$" },
    float = true, center = true, size = "1043 634" })

-- satty (annotation tool)
hl.window_rule({ name = "satty", match = { class = "^(com%.gabm%.satty)$" },
    center = true, float = true, opaque = true, animation = "slide down", size = "1115 624" })

-- -----------------------------------------------------------------------------
-- PICTURE-IN-PICTURE (PiP) & PINNED WINDOWS
-- -----------------------------------------------------------------------------

-- PiP: bottom-right corner, pinned
hl.window_rule({
    name  = "pip-global",
    match = { title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$" },
    float  = true,
    pin    = true,
    size   = "248 140",
    move   = "(monitor_w-window_w-20) (monitor_h-window_h-20)",
    no_dim = true,
    opaque = true,
})

-- Pinned Window Styling: green border for any pinned window
hl.window_rule({
    name  = "style-pinned-windows",
    match = { pin = true },
    no_dim       = true,
    border_color = "rgb(328E6E)",
    border_size  = 2,
    animation    = "slide down",
})

-- -----------------------------------------------------------------------------
-- GLOBAL WINDOW BEHAVIORS
-- -----------------------------------------------------------------------------

-- Persistent Size: floating windows remember their size on reopen
hl.window_rule({ name = "global-persistent-size",     match = { float = true }, persistent_size = true })

-- Prevent Maximize Events: force apps to respect tiling/floating rules
hl.window_rule({ name = "global-suppress-maximize",   match = { class = ".*"  }, suppress_event = "maximize" })

-- -----------------------------------------------------------------------------
-- XWAYLAND / PHANTOM WINDOW FIX
-- -----------------------------------------------------------------------------
-- Invisible XWayland tooltips/drag-previews that steal focus
hl.window_rule({
    name  = "fix-xwayland-phantom",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

-- -----------------------------------------------------------------------------
-- FULLSCREEN & VISUAL STYLING
-- -----------------------------------------------------------------------------
hl.window_rule({
    name  = "style-fullscreen",
    match = { fullscreen = true },
    border_color = "rgb(E2971F)",
    border_size  = 4,
    rounding     = 0,
})

-- -----------------------------------------------------------------------------
-- COMMON DIALOGS / FILE PICKERS
-- -----------------------------------------------------------------------------

-- Title-based dialogs
hl.window_rule({
    name  = "float-dialogs-title",
    match = { title = "^(Open|Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload|Authentication Required|Add Folder to Workspace|Choose Files|Confirm to replace files|File Operation Progress)(.*)$|^(.*dialog.*)$" },
    float  = true,
    center = true,
    size   = "816 537",
})

-- Class-based dialogs
hl.window_rule({
    name  = "float-dialogs-class",
    match = { class = "^(org.gnome.FileRoller|[Xx]dg-desktop-portal-gtk|.*dialog.*)$" },
    float  = true,
    center = true,
    size   = "816 537",
})

-- -----------------------------------------------------------------------------
-- LAYER RULES (rofi, mako, wlogout, waybar)
-- Check layers with: hyprctl layers
-- -----------------------------------------------------------------------------

-- Rofi: blur + dim backdrop
hl.layer_rule({ name = "blur-rofi",     match = { namespace = "rofi"           }, blur = true, dim_around = true, ignore_alpha = 0.0 })

-- Mako (notifications)
hl.layer_rule({ name = "mako",          match = { namespace = "notifications"  }, blur = true, ignore_alpha = 0.0 })

-- wlogout
hl.layer_rule({ name = "wlogout",       match = { namespace = "logout_dialog"  }, blur = true, ignore_alpha = 0.0 })

-- slurp screenshot selection: no blur, no animation
hl.layer_rule({ name = "selection",     match = { namespace = "selection"      }, blur = false, no_anim = true })

-- Waybar: blur + xray
hl.layer_rule({ name = "waybar_blur",   match = { namespace = "waybar"         }, blur = true, blur_popups = true, xray = true, ignore_alpha = 0.54 })

-- -----------------------------------------------------------------------------
-- SPECIAL WORKSPACE: magic (scratchpad)
-- -----------------------------------------------------------------------------
hl.workspace_rule({ workspace = "special:magic", gaps_out = 20, gaps_in = 6 })

hl.window_rule({
    name  = "style-magic-workspace",
    match = { workspace = "special:magic" },
    border_color = primary,   -- 'primary' is set by appearance.lua → hyprland-colors.lua
    border_size  = 1,
})

-- -----------------------------------------------------------------------------
-- GLOBAL MISC CONFIG (focus/fullscreen behavior)
-- -----------------------------------------------------------------------------
hl.config({
    misc = {
        -- 0 = do nothing, 1 = overlay new window, 2 = unfullscreen
        on_focus_under_fullscreen   = 2,
        -- Force new windows to spawn on the current workspace
        initial_workspace_tracking  = 1,
        focus_on_activate           = true,
    },
})
