-- DO NOT EDIT THIS FILE, if you want to configure something, edit the file
-- at this location: ~/.config/hypr/edit_here/source/workspace_rules.lua

-- ==============================================================================
-- HYPRLAND 0.55+ LUA WORKSPACE RULES
-- Last updated for Hyprland 0.55 (May 2026)
--
-- IMPORTANT: Since 0.55, hyprlang (.conf) is DEPRECATED in favor of Lua.
-- This file uses the new hl.* Lua API exclusively.
-- For the old hyprlang syntax, see the 0.54 wiki archive.
--
-- HOW THIS FILE IS ORGANIZED:
--
--   §1  TUI DATA INJECTION POINT  ......  Machine-written, leave the table here
--   §2  DYNAMIC WORKSPACE GENERATOR  ....  Loop-based rules for workspaces 1-10
--   §3  SMART GAPS  .....................  No gaps / borders when only one window
--   §4  SPECIAL WORKSPACES / SCRATCHPADS  Floating overlay workspaces
--   §5  NAMED / PROJECT WORKSPACES  .....  Semantic per-project environments
--   §6  MONITOR BINDING & PERSISTENCE  ..  Assign workspaces to specific outputs
--   §7  PER-WORKSPACE AESTHETICS  .......  Borders, rounding, gaps, animations
--   §8  PER-WORKSPACE LAYOUT OVERRIDES  .  dwindle / master / scrolling / custom
--   §9  RANGE RULES (Global Fallbacks)  .  Catch-all rules for workspace ranges
--   §10 GLOBAL WORKSPACE BEHAVIOUR  ....  hl.config() options that affect all ws
--       §10a  General (layout)
--       §10b  Dwindle layout
--       §10c  Master layout
--       §10d  Scrolling layout
--       §10e  Misc
--       §10f  Binds (navigation behaviour)
--
-- WORKSPACE IDENTIFIER QUICK REFERENCE:
--   "1" .. "N"          →  numbered workspace
--   "name:foo"          →  named workspace
--   "special:foo"       →  special (scratchpad) workspace
--   "r[X-Y]"            →  range selector  (e.g. "r[1-5]")
--   "w[tv1]"            →  selector: exactly 1 visible Tiled window
--   "w[tv2]"            →  selector: exactly 2 visible Tiled windows  (etc.)
--   "f[-1]"             →  selector: workspace has NO fullscreen window
--   "f[0]"              →  selector: workspace has a fullscreen window
--   "f[1]"              →  selector: workspace has a maximized window
--   "f[2]"              →  selector: fullscreen but state not sent to the client
--   "s[false]"          →  selector: exclude special workspaces
--   "s[true]"           →  selector: special workspaces only
--   Selectors can be combined with a space: "w[tv1]s[false]"
--   NOTE: selectors only match EXISTING workspaces at evaluation time.
-- ==============================================================================


-- ==============================================================================
-- §1  TUI DATA INJECTION POINT
-- The TUI populates `tui_workspace_data` and the engine loop below applies it.
-- Do not move or rename this table; the TUI depends on its exact location.
-- ==============================================================================
local tui_workspace_data = {
    -- The TUI will generate and insert rule tables here.
    -- Each entry is a table accepted by hl.workspace_rule().
    --
    -- Full list of supported keys (all optional except `workspace`):
    --
    --   workspace       (string)  -- REQUIRED. Identifier or selector (see above).
    --   monitor         (string)  -- Bind to monitor by name ("DP-1") or desc ("desc:...").
    --   default         (bool)    -- Make this the default workspace on its monitor.
    --   persistent      (bool)    -- Keep workspace alive even when empty.
    --   default_name    (string)  -- Human-readable display name (shown in bars, etc.).
    --   on_created_empty(string)  -- Shell command to run when workspace is first created
    --                             --   empty. Supports window rule flags, e.g. "[float] app".
    --   layout          (string)  -- Override layout: "dwindle" | "master" | "scrolling"
    --                             --   | "lua:<name>" (for custom Lua layouts).
    --   layout_opts     (table)   -- Layout-specific options (see §8 for details).
    --   gaps_in         (number)  -- Inner gap override (px). Accepts a single number or
    --                             --   a table {top, bottom, left, right}.
    --   gaps_out        (number)  -- Outer gap override (px). Same format as gaps_in.
    --   no_border       (bool)    -- Disable all window borders on this workspace.
    --   border_size     (number)  -- Override border thickness (px).
    --   no_rounding     (bool)    -- Disable corner rounding on this workspace.
    --   decorate        (bool)    -- Enable/disable decorations (shadows, etc.).
    --   animation       (string)  -- Override workspace switch animation style.
    --                             --   Values: "slide" | "slidevert" | "fade"
    --                             --           | "slidefade" | "slidefadevert"
    --                             --   Append a percentage for slidefade, e.g. "slidefade 20%"
    --
    -- EXAMPLES (uncomment to activate):
    --
    -- [Monitor Binding & Persistence]
    -- { workspace = "1", monitor = "DP-1",   default = true, persistent = true },
    -- { workspace = "2", monitor = "DP-1",   persistent = true },
    -- { workspace = "3", monitor = "eDP-1",  persistent = true },
    -- { workspace = "4", monitor = "desc:Dell Inc. U2722D 1234", default = true },
    --
    -- [Named Workspaces with Launch Commands]
    -- { workspace = "name:coding",  monitor = "DP-1",  on_created_empty = "kitty",
    --   gaps_in = 0, gaps_out = 0, no_border = true, no_rounding = true, decorate = false },
    -- { workspace = "name:browser", monitor = "DP-2",  on_created_empty = "firefox" },
    -- { workspace = "name:chat",    on_created_empty = "vesktop" },
    --
    -- [Special / Scratchpad Workspaces]
    -- { workspace = "special:scratchpad", on_created_empty = "kitty" },
    -- { workspace = "special:browser",    on_created_empty = "firefox", layout = "scrolling" },
    --
    -- [Aesthetic Overrides]
    -- { workspace = "8",  border_size = 8, animation = "slidevert", default_name = "visuals" },
    -- { workspace = "10", no_border = true, no_rounding = true },
    --
    -- [Layout Overrides — see §8 for full layout_opts reference]
    -- { workspace = "2", layout = "master",    layout_opts = { orientation = "top" } },
    -- { workspace = "3", layout = "scrolling", layout_opts = { direction = "right" } },
}

-- Engine Loop: Applies all TUI-generated rules to Hyprland.
for _, rule in ipairs(tui_workspace_data) do
    hl.workspace_rule(rule)
end


-- ==============================================================================
-- §2  DYNAMIC WORKSPACE GENERATOR (1-10)
-- Toggle `enforce_persistent_1_to_10` to keep workspaces 1-10 always alive,
-- even when all their windows are closed.
-- Useful for status bars that display a fixed set of workspace indicators.
-- ==============================================================================
local enforce_persistent_1_to_10 = false

if enforce_persistent_1_to_10 then
    for i = 1, 10 do
        hl.workspace_rule({
            workspace  = tostring(i),
            persistent = true,
        })
    end
end

-- Optional: Give each workspace a static display name.
-- The TUI can toggle this independently from persistence above.
local enforce_default_names_1_to_10 = false

local default_workspace_names = {
    [1]  = "I",
    [2]  = "II",
    [3]  = "III",
    [4]  = "IV",
    [5]  = "V",
    [6]  = "VI",
    [7]  = "VII",
    [8]  = "VIII",
    [9]  = "IX",
    [10] = "X",
}

if enforce_default_names_1_to_10 then
    for i = 1, 10 do
        hl.workspace_rule({
            workspace    = tostring(i),
            default_name = default_workspace_names[i],
        })
    end
end


-- ==============================================================================
-- §3  SMART GAPS  ("no gaps when only")
-- Removes gaps and borders when exactly one tiled window is on screen,
-- or when a window is in fullscreen/maximized state.
-- Replicates the popular "smartgaps" feature from other WMs.
--
-- Selector reference used here:
--   w[tv1]   → workspace with exactly 1 visible tiled window
--   f[1]     → workspace where a window is maximized
--   s[false] → exclude special/scratchpad workspaces
-- ==============================================================================
local enable_smart_gaps = false

if enable_smart_gaps then
    -- Remove gaps when there is only one tiled window
    hl.workspace_rule({ workspace = "w[tv1]s[false]", gaps_out = 0, gaps_in = 0 })
    -- Remove gaps when a window is maximized
    hl.workspace_rule({ workspace = "f[1]s[false]",   gaps_out = 0, gaps_in = 0 })

    -- Also remove borders and rounding so the window fills the screen cleanly
    hl.window_rule({ match = { float = false, workspace = "w[tv1]s[false]" }, border_size = 0, rounding = 0 })
    hl.window_rule({ match = { float = false, workspace = "f[1]s[false]"   }, border_size = 0, rounding = 0 })
end


-- ==============================================================================
-- §4  SPECIAL WORKSPACES / SCRATCHPADS
-- Special workspaces float over any monitor and can be toggled on/off.
-- They are identified by the "special:" prefix.
-- Toggle them with: hl.dsp.workspace.toggle_special({ name = "scratchpad" })
--
-- Notes:
--   • Each monitor gets its own independent instance of a special workspace.
--   • `misc.close_special_on_empty` (§10e) controls auto-close behaviour.
--   • `on_created_empty` launches an app the first time the workspace is shown.
-- ==============================================================================
local special_workspaces = {
    -- { name = "scratchpad", on_created_empty = "kitty" },
    -- { name = "browser",    on_created_empty = "firefox",   layout = "scrolling" },
    -- { name = "music",      on_created_empty = "spotify" },
    -- { name = "notes",      on_created_empty = "obsidian" },
}

for _, ws in ipairs(special_workspaces) do
    hl.workspace_rule({
        workspace        = "special:" .. ws.name,
        on_created_empty = ws.on_created_empty,
        layout           = ws.layout,  -- nil is safe; Hyprland ignores nil fields
    })
end


-- ==============================================================================
-- §5  NAMED / PROJECT WORKSPACES
-- Use "name:foo" identifiers for semantic, project-specific workspaces.
-- These can coexist alongside numbered workspaces.
-- You can navigate to them with: hl.dsp.workspace.name("coding")
-- ==============================================================================
local named_workspaces = {
    -- { name = "coding",  monitor = "DP-1",  on_created_empty = "kitty",
    --   gaps_in = 0, gaps_out = 0, no_border = true, no_rounding = true, decorate = false },
    -- { name = "browser", monitor = "DP-2",  on_created_empty = "firefox" },
    -- { name = "gaming",  monitor = "desc:Chimei Innolux Corporation 0x150C",
    --   no_border = true, no_rounding = true, decorate = false,
    --   layout = "scrolling" },
    -- { name = "chat",    on_created_empty = "vesktop" },
    -- { name = "music",   on_created_empty = "spotify" },
    -- { name = "virt",    on_created_empty = "virt-manager" },
}

for _, ws in ipairs(named_workspaces) do
    hl.workspace_rule({
        workspace        = "name:" .. ws.name,
        monitor          = ws.monitor,
        on_created_empty = ws.on_created_empty,
        layout           = ws.layout,
        layout_opts      = ws.layout_opts,
        gaps_in          = ws.gaps_in,
        gaps_out         = ws.gaps_out,
        no_border        = ws.no_border,
        border_size      = ws.border_size,
        no_rounding      = ws.no_rounding,
        decorate         = ws.decorate,
        animation        = ws.animation,
        default_name     = ws.default_name,
    })
end


-- ==============================================================================
-- §6  MONITOR BINDING & PERSISTENCE
-- Bind specific numbered workspaces to specific monitors.
-- `default = true` means Hyprland will show this workspace when the monitor
-- is first connected (or has no other workspace assigned).
-- `persistent = true` keeps the workspace alive even when empty.
--
-- Monitor name formats:
--   "DP-1"                            → connector name (use `hyprctl monitors`)
--   "eDP-1"                           → built-in laptop display
--   "desc:Dell Inc. U2722D ABCD1234"  → description-based (survives cable swaps)
-- ==============================================================================

-- Set `true` to activate, then fill in the monitor_bindings table below.
local enable_monitor_bindings = false

local monitor_bindings = {
    -- { workspace = "1",  monitor = "DP-1",   default = true,  persistent = true },
    -- { workspace = "2",  monitor = "DP-1",   persistent = true },
    -- { workspace = "3",  monitor = "DP-1",   persistent = true },
    -- { workspace = "4",  monitor = "DP-1",   persistent = true },
    -- { workspace = "5",  monitor = "DP-1",   persistent = true },
    -- { workspace = "6",  monitor = "eDP-1",  default = true,  persistent = true },
    -- { workspace = "7",  monitor = "eDP-1",  persistent = true },
    -- { workspace = "8",  monitor = "eDP-1",  persistent = true },
    -- { workspace = "9",  monitor = "eDP-1",  persistent = true },
    -- { workspace = "10", monitor = "eDP-1",  persistent = true },
}

if enable_monitor_bindings then
    for _, binding in ipairs(monitor_bindings) do
        hl.workspace_rule(binding)
    end
end


-- ==============================================================================
-- §7  PER-WORKSPACE AESTHETIC OVERRIDES
-- Override visual properties on a workspace-by-workspace basis.
-- These stack on top of / override the global decoration settings.
--
-- Available aesthetic keys:
--   gaps_in      (number | {top,bottom,left,right})  Inner gap override
--   gaps_out     (number | {top,bottom,left,right})  Outer gap override
--   border_size  (number)                            Border thickness in px
--   no_border    (bool)                              Disable borders entirely
--   no_rounding  (bool)                              Disable corner rounding
--   decorate     (bool)                              Toggle shadows / decorations
--   animation    (string)                            Animation style override
--                                                    "slide" | "slidevert" | "fade"
--                                                    "slidefade" | "slidefadevert"
--                                                    Add % for slidefade: "slidefade 20%"
--   default_name (string)                            Display name for bars / TUIs
-- ==============================================================================
local aesthetic_overrides = {
    -- Completely clean workspace — no distractions
    -- { workspace = "1",  gaps_in = 0, gaps_out = 0, no_border = true,
    --   no_rounding = true, decorate = false },

    -- Thick decorative border + vertical slide animation
    -- { workspace = "8",  border_size = 8, animation = "slidevert",
    --   default_name = "visuals" },

    -- Workspace 9 fades in/out (good for media/music workspaces)
    -- { workspace = "9",  animation = "fade" },

    -- Workspace 10 with custom inner/outer gaps per-side
    -- { workspace = "10", gaps_in = { top = 4, bottom = 4, left = 8, right = 8 },
    --   gaps_out = { top = 16, bottom = 16, left = 12, right = 12 } },
}

for _, override in ipairs(aesthetic_overrides) do
    hl.workspace_rule(override)
end


-- ==============================================================================
-- §8  PER-WORKSPACE LAYOUT OVERRIDES
-- Override the tiling layout on a per-workspace basis.
-- The global default layout is set in §10a.
--
-- Valid layout values:
--   "dwindle"     → Fibonacci/dwindle tiling (default in most configs)
--   "master"      → Master-stack layout
--   "scrolling"   → Scrolling tape layout (new in 0.54/0.55)
--   "lua:<name>"  → Custom layout defined with hl.layout.register() (new in 0.55)
--
-- layout_opts for "master":
--   orientation  (string)  "left" (default) | "right" | "top" | "bottom" | "center"
--
-- layout_opts for "scrolling":
--   direction    (string)  "right" (default) | "left" | "up" | "down"
-- ==============================================================================
local layout_overrides = {
    -- Master layout, master pane on top (horizontal split)
    -- { workspace = "2", layout = "master", layout_opts = { orientation = "top" } },

    -- Master layout, centered master pane
    -- { workspace = "3", layout = "master", layout_opts = { orientation = "center" } },

    -- Scrolling layout, tape grows to the right (default)
    -- { workspace = "4", layout = "scrolling", layout_opts = { direction = "right" } },

    -- Scrolling layout, tape grows downward
    -- { workspace = "5", layout = "scrolling", layout_opts = { direction = "down" } },

    -- Custom Lua layout (must be registered with hl.layout.register() elsewhere)
    -- { workspace = "6", layout = "lua:columns" },
}

for _, override in ipairs(layout_overrides) do
    hl.workspace_rule(override)
end


-- ==============================================================================
-- §9  RANGE RULES (Global Fallbacks)
-- Apply rules to a range of workspaces using the "r[X-Y]" selector.
-- These are evaluated for all workspaces in the range that EXIST at the time.
--
-- Common use cases:
--   • Set a different default layout for "overflow" workspaces (11+)
--   • Apply consistent gaps/aesthetics to a block of workspaces
--   • Mark a range as persistent
-- ==============================================================================
local enforce_global_fallbacks = false

if enforce_global_fallbacks then
    -- Example: workspaces 11–99 use scrolling layout by default
    hl.workspace_rule({
        workspace = "r[11-99]",
        layout    = "scrolling",
    })
end

-- Optional fine-grained range examples (toggle independently):

-- Make workspaces 1–5 use dwindle (left half of a dual-monitor spread)
local range_left_monitor = false
if range_left_monitor then
    hl.workspace_rule({ workspace = "r[1-5]",  layout = "dwindle" })
end

-- Make workspaces 6–10 use master (right half of a dual-monitor spread)
local range_right_monitor = false
if range_right_monitor then
    hl.workspace_rule({ workspace = "r[6-10]", layout = "master" })
end


-- ==============================================================================
-- §10  GLOBAL WORKSPACE BEHAVIOUR
-- hl.config() calls that affect workspace/window behaviour globally.
-- Multiple hl.config() calls are allowed; each one merges with existing config.
-- ==============================================================================


-- ----------------------------------------------------------------------------
-- §10a  General — global layout
-- (Note: gaps_in, gaps_out, and gaps_workspaces are configured visually in appearance.lua)
-- layout   : global default layout. "dwindle" | "master" | "scrolling" | "lua:*"
-- ----------------------------------------------------------------------------
hl.config({
    general = {
        layout          = "dwindle",  -- global default tiling layout
    },
})


-- ----------------------------------------------------------------------------
-- §10b  Dwindle layout
-- preserve_split : keep the split direction when toggling — KEEP THIS TRUE
--                  or the "toggle split" keybind will not behave as expected.
-- smart_split    : (bool) if true, splits based on window size rather than count.
-- smart_resizing : (bool) resize the side that is smaller rather than both.
-- force_split    : 0 = last window direction, 1 = always right/down, 2 = always left/up
-- pseudotile     : REMOVED in 0.55. Do not use.
-- ----------------------------------------------------------------------------
hl.config({
    dwindle = {
        preserve_split  = true,   -- required for toggle_split keybind to work
        smart_split     = false,  -- split based on window dimensions instead of count
        smart_resizing  = true,   -- resize the smaller side on manual resize
        force_split     = 0,      -- 0: last, 1: always right/down, 2: always left/up
    },
})


-- ----------------------------------------------------------------------------
-- §10c  Master layout
-- new_status        : "master" | "slave" | "inherit" — where new windows go.
--                     "slave"   = all new windows go to the slave stack (default)
--                     "master"  = new windows always become the master
--                     "inherit" = new window inherits the status of the focused one
-- new_on_top        : (bool) insert new slave windows at the TOP of the stack.
-- mfact             : (float 0.0-1.0) fraction of the screen the master pane takes.
-- orientation       : "left" | "right" | "top" | "bottom" | "center"
--                     Controls which side of the screen the master pane occupies.
--                     Use "center" for a centered master with stacks on both sides.
-- allow_small_split : (bool) allow adding extra master windows in horizontal-split
--                     style when there are multiple masters.
-- special_scale_factor : (float 0.0-1.0) scale factor for windows on special
--                        (scratchpad) workspaces when using master layout.
--
-- NOTE: always_center_master and inherit_fullscreen do NOT exist in stock
-- Hyprland. They originated in third-party plugins (hyprNStack etc.).
-- Per-workspace centering is set via layout_opts = { orientation = "center" }
-- in hl.workspace_rule() — see §8.
-- ----------------------------------------------------------------------------
hl.config({
    master = {
        new_status           = "slave",  -- new windows go into the slave stack
        new_on_top           = false,    -- append to bottom of slave stack
        mfact                = 0.55,     -- master pane takes 55% of the screen
        orientation          = "left",   -- master pane on the left
        allow_small_split    = false,    -- extra horizontal master splits
        special_scale_factor = 0.8,     -- scale of windows in special workspaces
    },
})


-- ----------------------------------------------------------------------------
-- §10d  Scrolling layout
-- Introduced in Hyprland 0.54, refined in 0.55.
--
-- fullscreen_on_one_column : (bool) when a workspace has only one column, treat
--                            that column as fullscreen (window fills monitor).
--                            Defaults to false.
--
-- IMPORTANT — keys that do NOT exist as global scrolling config:
--   • column_default_width  → set per-window via hl.window_rule scrolling_width
--   • reorder               → not a config option
--   • direction             → per-workspace only, via layout_opts = { direction = "right" }
--                             in hl.workspace_rule() — see §8
-- ----------------------------------------------------------------------------
hl.config({
    scrolling = {
        fullscreen_on_one_column = false,  -- single-column workspace fills screen
    },
})


-- ----------------------------------------------------------------------------
-- §10e  Misc — special workspace & focus behaviour
-- close_special_on_empty   : (bool) auto-close special workspace when last
--                            window in it is closed.
-- focus_on_activate        : (bool) focus a window that requests activation
--                            (e.g. urgency hint / xdg_activation).
-- on_focus_under_fullscreen : behaviour when a window is focused while another
--                             is fullscreen on the same workspace.
--                             0 = do nothing (new window stays behind)
--                             1 = new window takes over (unfullscreens current)
--                             2 = unfullscreen current, then fullscreen the new one
--
-- NOTE: this key was previously called new_window_takes_over_fullscreen and was
-- renamed to on_focus_under_fullscreen. The old name errors on 0.55+.
-- ----------------------------------------------------------------------------
hl.config({
    misc = {
        close_special_on_empty    = true,   -- clean up empty scratchpads
        focus_on_activate         = false,  -- don't steal focus on activation
        on_focus_under_fullscreen = 0,      -- 0 = stay behind | 1 = take over | 2 = swap fs
    },
})


-- ----------------------------------------------------------------------------
-- §10f  Binds — workspace navigation behaviour
-- workspace_back_and_forth     : (bool) re-dispatching to the active workspace
--                                switches back to the previously active one.
-- allow_workspace_cycles       : (bool) cycling past workspace 1 wraps to the
--                                highest-numbered, and vice versa.
-- workspace_center_on          : 0 = cursor stays, 1 = cursor moves to center of
--                                the new workspace's focused window,
--                                2 = cursor moves to center of the monitor.
-- hide_special_on_workspace_change : (bool) hide open special workspaces when
--                                    you switch to a different normal workspace.
-- movefocus_cycles_fullscreen  : (bool) movefocus wraps around into/out of
--                                fullscreen windows.
-- window_direction_monitor_fallback : (bool) moving a window past the edge of a
--                                    monitor moves it to the adjacent monitor.
-- ----------------------------------------------------------------------------
hl.config({
    binds = {
        workspace_back_and_forth          = false, -- toggle back on re-dispatch
        allow_workspace_cycles            = false, -- wrap around at ends
        workspace_center_on               = 0,     -- 0 = cursor stays in place
        hide_special_on_workspace_change  = false, -- keep scratchpad visible on switch
        movefocus_cycles_fullscreen       = true,  -- movefocus wraps around fullscreen
        window_direction_monitor_fallback = true,  -- cross-monitor window movement
    },
})
